### ISSUE TITLE
Create Responsive Menu

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#105]
Begin building a mobile menu.  Idea here is to update the main template for the site and get the basics in place.  The specific styling can be done in a follow up ticket

() In the styleguide: 
() Build menu mobile first
() Create a standard mobile menu
() Create a smooth animation for showing and hiding the mobile menu.
() Create an animation for the hamburger e.g https://codepen.io/designcouch/pen/Atyop

**Comment by aweingarten** [comment]
@jonraedeke @sarahjean thinking we can at least start building the mobile menu and do some site basics while we debate the design.

**Comment by charlieartist** [comment]
@aweingarten Also, would be good to prepare contingencies for non-JS users in the interest of progressive enhancement.

**Comment by aweingarten** [comment]
it's 2017 who are these non-js users?

**Comment by charlieartist** [comment]
This is DC. Even at FNM, we have plenty of Web resources blocked due to security protocols. For a lot of my work, I'm using a third-party VPN over the guest WiFi just to access some Websites. Also, back at Natcher, third-party font serving (Google) was also blocked to in-house machines.

**Comment by aweingarten** [comment]
work complete
