### ISSUE TITLE
Style a footer

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#106]
() Create a styleguide component for the footer.
() should have a link to the privacy policy page.  If one does not exist create one on dev. 
() "Graciously hosted by NIH NIH Library"

Questions:
() Should we have a fork us on github link?  
() Should we have a link to code of conduct?
() Anything else?

**Comment by aweingarten** [comment]
@timwood thoughts?

**Comment by charlieartist** [comment]
@aweingarten @timwood I put items in the footer to get the conversation started. Ideally, our content team should be looking at this, and giving feedback. It's also advisable to plan for more space here, allowing that "magic footer" to hold links that shouldn't be in the main navigation. It's a diplomatic way to solve contentious IA disputes. So far, I've only heard from @timwood on the IA in general.

**Comment by timwood** [comment]
Fork us on github could be cool, but we have a rather complex codebase, so the barrier to entry on contributing with PRs is high (it's not like the code is just MD content rendered into static site). BUUUUT this is a Drupal conference, so you never know who might want to contribute.

**Comment by aweingarten** [comment]
eh I saw it on badcamp.  Thinking that other camps could steal stuff.  I like to look at other camp's code bases.  That being said not married to the idea.

**Comment by aweingarten** [comment]
another good example link:  https://www.fldrupal.camp/

**Comment by timwood** [comment]
I like how FLDrupal camp repeats their entire menu in the footer, like we did in 2015.

**Comment by timwood** [comment]
I also like what DrupalCamp NJ has.
<img width="927" alt="screen shot 2016-11-19 at 7 01 16 pm" src="https://cloud.githubusercontent.com/assets/91050/20459321/b1850a98-ae8a-11e6-83f6-147e38e68e9b.png">

Let's do the "Fork us"!

**Comment by jonraedeke** [comment]
Here's the footer in the latest mockup from @charlieartist .
<img width="890" alt="footer" src="https://cloud.githubusercontent.com/assets/2054715/20912353/b601f1e4-bb3c-11e6-948c-b76749cd1d3d.png">

**Comment by jonraedeke** [comment]
I'm going to close this since the footer component is styled in the styleguide and merged in. I'll open a new ticket for creating the footer block and adding it to a region in the actual theme.
