### ISSUE TITLE
Create a Sponsor Content Type

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#107]
Create a new sponsor feature here:
- https://github.com/drupal-cod/sponsors

Add the following Fields
- Sponsor Url:  Title+Url
- Logo (image)
- Sponsorship level (Taxonomy Term)
- Related Attendees (User entity reference)

Need configurable view block that allows you to select a Sponsorship level  and only display the teasers for those sponsors.

**Comment by charlieartist** [comment]
Also of critical importance--a flag or other indicator to reference payment status. This can be a major source of anxiety for accounts receivable.

**Comment by jdearie** [comment]
@charlieartist - it's my understanding that we are handling payment etc of sponsors external to the site... we're using eventbrite. if we'er talking about for future, sure... but right now we just need to be able to display sponsors on the site...

**Comment by jdearie** [comment]
We need a view (and likely blocks/panels) for all sponsors by sponsorship level:
Level (# available) (levels listed in highest cost to lowest)

Core (3)
Coffee (1)
Contributor (4)
Mentor (2)
Sprinter (2)
Exhibitor (20)
Supporter (unlimited)
Personal (unlimited)
Training (4-8)

**Comment by aweingarten** [comment]
Work completed and merged by @malikkotob

**Comment by jdearie** [comment]
Sponsor sort order (highest to lowest)

Core (3)
Coffee (1)
Contributor (4)
Mentor (2)
Sprinter (2)
Training (4-8)
Exhibitor (20)
Supporter (unlimited)
Personal (unlimited)
