### ISSUE TITLE
Fix Jittery Main Menu behavor for authenticated users

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#157]
When logged in the second level nav items seem to loose focus on hover

**Comment by timwood** [comment]
This is happening for anonymous now. See #160

**Comment by jdearie** [comment]
i don't see this as anon... can we close?

**Comment by jonraedeke** [comment]
I don't see a jittery menu either. Feel free to re-open if you do.
