### ISSUE TITLE
Remove the Page title from the block layout config

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#158]
Go to the block layout and remove page title.  
export CMI and commit the changes that account for the block title.

**Comment by lkopacz** [comment]
I will take this on.

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/161

**Comment by aweingarten** [comment]
Merged fixed.
