### ISSUE TITLE
Fix Z-index of Nav Dropdown

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#160]
<img width="849" alt="screen shot 2017-02-08 at 12 15 50 am" src="https://cloud.githubusercontent.com/assets/6517820/22724444/1e0ff28e-ed94-11e6-9999-43604c09ca1b.png">

**Comment by aweingarten** [comment]
@jonraedeke or @lkopacz should be a quick fix!

**Comment by timwood** [comment]
Focus is also lost (the menu closes) when you move your mouse down the menu. This happens as soon as your mouse gets to the hero graphic.

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/162

**Comment by aweingarten** [comment]
Verified on Dev.  Closing!
