### ISSUE TITLE
Update Hero Image Placement

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/Drupal-GovCon-2017#165]
Currently, on the homepage mock, the hero image appears to be in the main content area, and should be in the hero area immediately below the navbar. In addition, it's full width, while the main body area is not.

Please refer to the comp for placement:
![1880-govcon17_sitemock-02-desktop_01home_v07](https://cloud.githubusercontent.com/assets/3085730/22809797/ae6ee262-ef02-11e6-8fd2-14d69826a8f8.png)

**Comment by charlieartist** [comment]
I moved this custom block to the header region last night, and deleted the instance in the main content area.

**Comment by aweingarten** [comment]
Fixed!
