### ISSUE TITLE
Update Site Structure to match menu structure (or vice versa)

### ISSUE THREAD

**Issue by vadnguyen** [Drupal4Gov/Drupal-GovCon-2017#168]
From @jess - "after talking with @dmkelner  i updated and added some content to the site. I didn't touch the home page (swear)... but it's no longer there.  When you look at the menu structure, and the individual nodes, they correct site structure is there (pages are in the appropriate groupings AND in the right order)... however what's being displayed on the site does not match what the menu structure/nodes say it should be.  not a huge deal but an FYI"

**Comment by bendygirl** [comment]
This appears complete since we've launchd. Closing
