### ISSUE TITLE
Update external links to include visual indicator

### ISSUE THREAD

**Issue by vadnguyen** [Drupal4Gov/Drupal-GovCon-2017#169]
1: Add the module to the codebase by doing the following `composer require drupal/extlink`
2: Commit the composer.json and composer.lock as a single commit.
3: Enable the module locally, configure it.
4: `drush cex`
5: Commit the relevant CMI

See here for details about adding new composer dependencies
https://www.jeffgeerling.com/blog/2017/tips-managing-drupal-8-projects-composer

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/170

**Comment by aweingarten** [comment]
Confirmed on Dev!
