### ISSUE TITLE
Govcon logo doesn't line up vertically with main menu items

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#172]
Desktop:
<img width="542" alt="screen shot 2017-02-14 at 8 48 10 am" src="https://cloud.githubusercontent.com/assets/91050/22931374/5ef515e2-f292-11e6-9a67-00949e437727.png">

Mobile:
<img width="321" alt="screen shot 2017-02-14 at 8 47 45 am" src="https://cloud.githubusercontent.com/assets/91050/22931373/5ef0a4a8-f292-11e6-941b-f3bfde682a34.png">

**Comment by dmkelner** [comment]
And should be a larger target.

**Comment by charlieartist** [comment]
This should not display for desktop. I have it in notes to address.

**Comment by jonraedeke** [comment]
I can fix this one. @charlieartist , is the big hero with logo supposed to be on all the interior pages as well? Just making sure there is a way to get back to the home page on desktop if the small logo is hidden.

**Comment by aweingarten** [comment]
fixed
