### ISSUE TITLE
Don't apply external link visual indicator to Twitter & Facebook links in footer

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#173]
And anywhere else special, styled links like this reside?

Probably easiest to use Extlink modules CSS matching configuration feature to exclude those selectors.

<img width="304" alt="screen shot 2017-02-14 at 8 42 36 am" src="https://cloud.githubusercontent.com/assets/91050/22931444/a8c20266-f292-11e6-9320-16bbd07c7297.png">

**Comment by lkopacz** [comment]
Thanks for catching this @timwood. Should be fixed now. 

https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/175

**Comment by jdearie** [comment]
Closing since it looks like this is good now.
