### ISSUE TITLE
Add links to 2015 and 2016 static archive sites to footer

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#191]
For now we've added links to archive sites on the /about page, but it might be good to have in the footer like how these sites did it:

https://www.fldrupal.camp/
![image](https://cloud.githubusercontent.com/assets/91050/23079050/2a1fdbb6-f519-11e6-9de9-52853591a61b.png)

https://www.drupalcampnj.org/
![image](https://cloud.githubusercontent.com/assets/91050/23079043/239977fc-f519-11e6-943e-c3faec54c6bf.png)

Also related to #79

**Comment by bheatonf1** [comment]
@timwood Do we have links for these archived sites?
