### ISSUE TITLE
Fix CloudFlare cache purging

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#201]
After entering the CloudFlare API credentials, when editing a node, the CloudFlare cache for that page is still not purged. The resulting error is related to our CloudFlare account being the free version which doesn't support purging by tag. I didn't see a Drupal config option for CloudFlare module to purge by individual path. Not sure how to resolve this without paying for CloudFlare or disabling caching.

**Comment by bendygirl** [comment]
@timwood this is working now since the site is up. If anyone paid for cloudflare, let Kirsten know for budgeting. Recommend closing.
