### ISSUE TITLE
Contact page not configured

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#203]
The contact link in the footer goes to a blank contact page...  which had this message "The contact form has not been configured. Add one or more forms ."

So I created a contact form... but I don't see how I get the form onto the actual page. ???
/admin/structure/contact shows the form

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/210

**Comment by mikemadison13** [comment]
@jdearie this has been merged and should be on its way to the dev site

**Comment by jdearie** [comment]
reopening since i noticed today that /contact is not available to anon users.
users get "You are not authorized to access this page."
