### ISSUE TITLE
Fix Order of Elements on Homepage

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/Drupal-GovCon-2017#205]
Currently, the homepage CTA blocks are above the main content. To fix it, the order should be:

- Main page content
- CTA Blocks

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/211

**Comment by charlieartist** [comment]
IOW, this is good to close now, isn't it.

**Comment by sarahjean** [comment]
Hasn't been deployed to prod yet
