### ISSUE TITLE
Individual Donations

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#208]
ideally we have the ability to allow users to choose to donate to drupal4gov.  ideally upon registration and then also a general button for folks to donate anytime.

**Comment by timwood** [comment]
@jdearie Is it important for donation on registration to be integrated into the entire registration flow, not taking the user away from the task of registering? Would it be good enough to leverage (and highlight) the same general donate button, at the end of the registration process? Integrating donation in registration workflow/process likely means more work and probably contrib modules.

Is this something that needs some UX / Design thought before decisions are made about implementation? @charlieartist @sarahjean @jonraedeke

**Comment by jdearie** [comment]
we can't accept donations until we are formally incorporated
