### ISSUE TITLE
Style Sponsor Block and Page

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/Drupal-GovCon-2017#209]
![1880-govcon17_wireframe-02-desktop_sponsors_v03](https://cloud.githubusercontent.com/assets/3085730/23342005/45a8ce20-fc20-11e6-98c2-728e765eb53a.png)
![1880-govcon17_wireframe-02-desktop_home_v03](https://cloud.githubusercontent.com/assets/3085730/23342008/45d96d96-fc20-11e6-8519-40436df52a1e.png)
![1880-govcon17_wireframe-01-mobile_sponsors_v03](https://cloud.githubusercontent.com/assets/3085730/23342007/45d4d0a6-fc20-11e6-9dcc-421d6aa01805.png)
![1880-govcon17_wireframe-01-mobile_home_v03](https://cloud.githubusercontent.com/assets/3085730/23342006/45d38f0c-fc20-11e6-89d6-7cc4d8792514.png)

Create sponsor page, with organizations listed in descending order, grouped by sponsor level. In addition, create a block to display top-level sponsors for homepage.

For content and layout, wireframes are attached.

**Comment by jdearie** [comment]
just make sure the levels match what's in the prospectus (as listed on /sponsor) - they are different this year.

**Comment by aweingarten** [comment]
@charlieartist,
Here is the sass for styling:

https://github.com/Drupal4Gov/Drupal-GovCon-2017/blob/master/docroot/themes/custom/twentyseventeen/sass/components/sponsor-listing/_sponsor-listing.scss

https://github.com/Drupal4Gov/Drupal-GovCon-2017/blob/master/docroot/themes/custom/twentyseventeen/sass/components/sponsor/_sponsor.scss

**Comment by jdearie** [comment]
can we please move Training Sponsors above Exhibitor Sponsors on the page please?

**Comment by charlieartist** [comment]
@jdearie Thanks for the info--we'll get it moved. Also, copy was added to the homepage block, and will be coming to the main page as well:
Interested in sponsoring Drupal GovCon? See what's available here.

**Comment by dmkelner** [comment]
The home page needs styling as well. Logos are way too big and look unprofessional.

**Comment by aweingarten** [comment]
complete
