### ISSUE TITLE
Create Splash Page

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/Drupal-GovCon-2017#21]
Initial splash page with basic information for GovCon 2017, to be displayed until Drupal build is ready to be shown to public. Pending consultation with the team on how to implement--will most likely be static splash page, HTML/CSS, with minimal JS.

**Comment by onelittlebecca** [comment]
do we have design for next year or still in the works?

**Comment by charlieartist** [comment]
Becca--it's still in the works. Adam is posting up some ideas from other sites, but so far, we don't have consensus on the branding. As soon as that's done, we will be moving forward. I'm already working on getting UX and design patterns up, and with Sarah on a style guide.

**Comment by timwood** [comment]
Now that we have 2015 and 2016 static site archives in the Git repo, can we make sure we link to those somewhere, possibly on the splash screen?

**Comment by aweingarten** [comment]
done
