### ISSUE TITLE
Setup Ticket/Event Registration 

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#213]
This issue is related, but separate, from User Registration (issue #30)

The fields listed below should be included in the ticket registration process.  Asterisk indicates a required field.

**Attendee e-mail address** [text field] *
_Enter the e-mail address of the recipient who will use this ticket. If you are registering for someone else, please enter their email address._

[checkbox] Email redemption code to above address and recipient will complete registration later.

_Note: Registration is not complete until recipient fills out the registration form_

First name * [text field]
Last name * [text field]
Job title * [text field]
Organization * [text field]
Country * [select] - see below for list of entries
City *  [select]
State *  [select]
~~ZIP code * [number field]~~

Gender * [select]
 Prefer not to share
 Male
 Female
 Other

**T-shirt size (sizes are unisex)***  [select]
XS
S
M
L
XL
XXL
No thanks, I don't want a shirt

**Meal * [select]**
None 
No Restrictions 
Vegetarian 
Vegan 
Gluten Free 
Halal 
Kosher 
Special Diet
Special diets: [text area]

Which days do you plan to attend Drupal GovCon? * [checkbox]
[descriptive text] This helps us get an accurate count for lunch.  Don't worry, you can still attend all three days regardless of what select here.  Give us your best guess.
Monday 
Tuesday
Wednesday

Is this your first time attending Drupal GovCon? *  [select]
This is my first Drupal GovCon!
I’ve attended once before 
I've attended 2-3 Drupal GovCons 
I’ve attended 4 or more Drupal GovCons (formerly known as Drupal Gov Days)

Are you attending sprints? *   [select]
Yes, I'm going to sprint on Core or Contrib.
Yes, I want to be a sprint mentor.
No, I am not attending sprints.
I haven't decided yet.

How did you hear about Drupal GovCon? *  [select]
My company sent me
A friend or colleague referred me
drupalgovcon.org or drupal4gov.org
A Drupal camp, meetup, or sprint
Social media
Other

Sign up for news! * [checkboxes]
 Sign me up for Drupal GovCon news
 Sign me up for Drupal4Gov infrequent educational / training news
 Sign me up for infrequent sponsor news and promotions
 No thanks, I'm subscribed already or get my Drupal news elsewhere

How would you describe your company? *  [select]
Federal Agency
State Agency
Local/City Agency
Digital Agency, Design or Development Shop
Hosting Company
Independent Software Vendor (ISV)
Media Partner/PR Firm
Recruiter/Staffing
Systems Integrator (SI)
Training/Books
Other

Please select your organization's size * [select]
1
2-10
11-50
51-100
101-500
501-1,000
1,001-10,000
10,000+
Don’t know/Not sure

Please select the industries that you work in (select all that apply) * [checkbox]
Advertising, Marketing, PR
Agriculture, Forestry, Fishing
Construction
Education
Finance, Insurance, Real Estate
Government
Hospitality, Travel
Manufacturing
Media
Medical, Pharma, Biotech
Nonprofit
Retail or Wholesale Trade
Services
Other

How do you use Drupal? * [select]
I am a freelancer
I work for a Drupal site owner (eg. NBCUniversal, economist.com, etc)
I work for a Drupal web development, digital, or design agency
I work for a government agency using Drupal
I am evaluating Drupal
I provide Drupal hosting solutions
I provide tools/services that integrate with Drupal
Other

What is your level of Drupal experience? * [select]
I'm just exploring Drupal
I'm a Drupal beginner
I have some Drupal skills
I have strong Drupal expertise
I am a Drupal master

What is your role at your organization? * [select]
Business (Marketing / Sales / Bus. Dev)
C Level (CEO/CMO/CTO, Director, etc.)
Technical Manager
Front end (Developer, Themer, UX, Designer)
~~Site administrator (User manager, Content manager)~~
Site Builder
Content Manager
Devops
Full stack developer
Project management
Trainer
I don't use Drupal yet; I'm evaluating it for future use
Other

In my organization, I have input on the purchase of the following: * [select]
Content Management Systems
Customer Relationship Management Tools
Digital Asset or Document Management Tools
Dev Ops Tools
E-Commerce Tools
Hosting
Marketing Software
Project Management Software
Other

[checkbox] **Show on attendee listing page**

Participation Release *
[checkbox] Show on attendee listing page
[checkbox] Contact me closer to the event regarding on-site volunteer opportunities.
[checkbox] Please contact me to discuss my specific on-site accessibility needs.

Participation Agreements * 
[checkbox] Yes, I have read and will adhere to the Drupal GovCon Code of Conduct (link to /code-conduct) and Media Policy (link to /media-policy).

**Comment by alisonjo2786** [comment]
RELATED #292 and #286

**Comment by aweingarten** [comment]
Complete and deployed

**Comment by timwood** [comment]
Participant Release section was accidentally marked as required in the original ticket above. I've removed the star for that item.
