### ISSUE TITLE
add brought to you by Drupal4Gov in the footer

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#215]
Relates to #191 

somewhere in the footer - perhaps above or below the NIH text.

"Brought to you by Drupal4Gov"  link to www.drupal4gov.us
Maybe include the D4G logo?  (see twitter.com/govdrupal or the drupal4gov website for logos)

**Comment by onelittlebecca** [comment]
![d4g](https://cloud.githubusercontent.com/assets/9077705/24413427/626286f0-13a9-11e7-81ef-d433c0ec43ed.png)

just so y'all have it here

**Comment by bendygirl** [comment]
Let's do this:

Drupal GovCon is graciously hosted by the NIH Library and made possible by our generous sponsors, wonderful volunteers and brought to you by Drupal4Gov (link to www.drupal4gov.us).

**Comment by bheatonf1** [comment]
@jdearie is this task complete? Can we close it?

**Comment by jdearie** [comment]
nope.  the footer is still the old footer.
