### ISSUE TITLE
Enable User Registration + Update Permissions

### ISSUE THREAD

**Issue by mikemadison13** [Drupal4Gov/Drupal-GovCon-2017#218]
Currently the User Registration is disabled on the site despite work being done on https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/30. This ticket is to enable user registration (and save to CMI) and update permissions so that anon/registered users can use the appropriate features.

- [x] Enable User Registration (and add to CMI)
- [x] Give anon/auth users access to the Simple Text text format
- [x] Give anon/auth users access to view user profiles

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/323

**Comment by aweingarten** [comment]
done
