### ISSUE TITLE
Style User Registration Form

### ISSUE THREAD

**Issue by mikemadison13** [Drupal4Gov/Drupal-GovCon-2017#219]
A few styling issues that should be looked at on the user registration form (re: https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/30)

- [ ] Visually there is no difference between the required / not required fields
- [ ] Updating spacing between fields
- [ ] Ensure styling of form elements is consistent with the rest of the visual design (buttons, etc.)

**Comment by alisonjo2786** [comment]
#287 was duplicate of this

**Comment by aweingarten** [comment]
done
