### ISSUE TITLE
Replace Custom Block for Menu with a Drupal Menu Block

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#239]
Currently we are using a totally custom block which lacks a lot of the capabilities of the drupal menu block. It lacks ordering and show/hiding menu elements.  Replace with drupal menu block

**Comment by jonraedeke** [comment]
I'm reopening this since I didn't realize this is not swapped on prod yet.

**Comment by aweingarten** [comment]
Done!
