### ISSUE TITLE
Ticket Bugs

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#259]
[] Remove save draft
[]  Need visual indicator for required fields
[]  State/province not populating
[] Can’t register

**Comment by bheatonf1** [comment]
I can probably work on this - do we want to use 'address' module?

**Comment by alisonjo2786** [comment]
@aweingarten Issue can be closed, I think.

**Comment by alisonjo2786** [comment]
Seems to be complete or no longer relevant or something.
