### ISSUE TITLE
Need a view/block which shows a user's registration

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#260]
### Business Requirements
- As a user when I visit the users page I want to see my ticket registrations.

### Technical Requirements
- [ ] Create a block or view which shows all the submissions for a given user.  

### Technical Note:
It looks like the UID data is at least in the webform_submission's table so this is is theoretically possible even if worst case we need to write a custom DB query

**Comment by bheatonf1** [comment]
https://www.drupal.org/project/webform_views handles integration of webform submissions with views. Created a view/block display with contextual filter for logged in user, relationship to uid of webform submitter  - hide view if no results. place block in content area of /user/* pages. Updated form permissions to allow viewing/editing of users own forms.

**Comment by aweingarten** [comment]
done!
