### ISSUE TITLE
Travel page: NIH/Natcher address

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#270]
### Requirements
- [ ] Make address on Travel page "clickable" -- see below.

#### Background
Address for Natcher on Travel page should have that fancy HTML5 thing that makes the address clickable.
https://capitalcampdev.prod.acquia-sites.com/travel

![image](https://cloud.githubusercontent.com/assets/2660348/24973318/4ea4d1ba-1f8c-11e7-93eb-35a30c384af8.png)

**Comment by jonraedeke** [comment]
We'd have to allow the <address> tag in the text format settings.
