### ISSUE TITLE
[ignore] Language tweaks (ongoing notes)

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#271]
https://capitalcampdev.prod.acquia-sites.com/present

* Title (and menu link text) should be "be a speaker" not "become" -- it's just awkward/non-normal as "become"
* First heading, I'm 92% sure "will" should be lowercased ("Session Submissions Will Open Soon")
* First section, last sentence -- "Sessions are submitted via track (see below), and experience level (beginner, intermediate, advanced)." >> Suggested edit: "Sessions are organized [or "grouped"] by track (see below) and experience level (beginner, intermediate, advanced)." >> i.e. change "submitted via" and remove comma after (see below)

**Comment by jdearie** [comment]
title and menu text taken from drupalcon site menu - so this issue may be more subjective; tabling for now.

first comment no longer applicable as language changed

made changes suggested in third item
