### ISSUE TITLE
Log in page: superfluous User Sessions heading

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#274]
https://capitalcampdev.prod.acquia-sites.com/user/login
![image](https://cloud.githubusercontent.com/assets/2660348/25025393/14981b0a-2070-11e7-9506-d80f291135d3.png)

**Comment by alisonjo2786** [comment]
(now I'm seeing it when I'm logged-in, too, so really, prob just need to hide this heading/block/whatever when there are no user sessions, right?)

**Comment by timwood** [comment]
@aweingarten I can do this one since I'm also editing the session view in #315.

**Comment by timwood** [comment]
I set "Hide block if the view output is empty" to Yes, so the view doesn't render if there are no sessions, but instead should we have "No results" text with a message about submitting a session?

> You haven't submitted a session yet, why not [submit one](/node/add/session)?

**Comment by jdearie** [comment]
I like that idea even better

**Comment by timwood** [comment]
Thanks!

**Comment by jdearie** [comment]
Only thing - if a user hasn't logged in her but HAS submitted a session that txt might confuse them.

**Comment by timwood** [comment]
I'll make sure the view only displays when logged in.
