### ISSUE TITLE
Register / new user workflow is confusing

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#277]
## Technical Requirements
() after a user creates a new account redirect them to the ticket registation page.

##  Initial Research

````
Adam tried this but couldn't make it work.

/**
 * Implements hook_form_FORM_ID_alter().
 */
function capitalcamp_glue_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // @todo come up with a more elegant approach here.

  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_capitalcamp_glue_user_register_form_submit';
}

/**
 * Custom submit handler for registration form.
 */
function _capitalcamp_glue_user_register_form_submit($form, FormStateInterface $form_state) {
  // Set redirect to login form.
  $url = \Drupal\Core\Url::fromUri('internal:/form/registration');
  $form_state->setRedirectUrl($url);
}
````

Scenario: 

New person clicks "Register" > "Create new account" > Fills in whole page > Click "create new account" button -- you end up on the homepage with a success message that says "Registration successful, you are now logged in." -- which implies that they've **_registered_**, as in, for the conference (since they got to that point via the "register" button), when of course all they've done is register as a new user on the website.

**Comment by jdearie** [comment]
Agreed. We need additional language on the user registration confirmation page that tells folks they are registered on the site but NOT for the event.

The Register button on the confirmation page gives no indication that it will take you to the ticket registration.

While I understand on a technical level why user registration and ticket registration are separate, to most users they are not. Perhaps we could go straight to ticket registration but require users be authenticated to fill out the form. Then, if they aren't registered for an account they will be prompted to do so.

**Comment by alisonjo2786** [comment]
So technically that's what's sorta happening now -- that's why when you click "Register" and you're anonymous, it says "You must be logged in to view this page" or whatever the language is.  I think then it may have been intended for the user login/new account form to drop you off at the ticket reg form after you've authenticated, but it just isn't set up to do that yet?

**Comment by aweingarten** [comment]
"Congrats you now have an account on drupalgovcon.org.  Please go ahead and register for the event!"

**Comment by alisonjo2786** [comment]
@aweingarten @jdearie  Prob can mark this duplicate of #280 and #279 , yes?

**Comment by alisonjo2786** [comment]
Covered in #280 and #280
