### ISSUE TITLE
Homepage title

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#278]
### Requirements
- [x] Change site homepage title -- prob just remove page title overall, leave as just site name (but if that's not what people want, change it from "Updates" to... "Welcome" or "Drupal GovCon 2017 Updates" or similar).
  - **If we aren't sure what the new title should be, short-term fix:** Remove page title from the title, leave as just site name, and revisit later.

#### Background
Homepage page title seems to be "Updates" (or "Drupal GovCon 2017 - Updates") -- prob should just be the site name or like, "welcome" or whatever -- but site name seems best, right...?

**Comment by alisonjo2786** [comment]
@charlieartist Does that make sense / what do you think?

**Comment by charlieartist** [comment]
Agreed--there ought to be a welcoming UX, and this includes content!

**Comment by alisonjo2786** [comment]
@aweingarten at least the "short term fix" suggestion i added to ticket description should be done this week, IMO.

**Comment by aweingarten** [comment]
made title DrupalGovcon 2017

**Comment by alisonjo2786** [comment]
@aweingarten Drupal GovCon, two words! (of course if that's what you did and you just typod here​, nm!)

**Comment by alisonjo2786** [comment]
(is it weird to have it be Drupal GovCon 2017 | Drupal GovCon, or is that a normal thing?) ( @jdearie ?)

**Comment by aweingarten** [comment]
@alisonjo2786 This is out of the box drupal behavior

**Comment by alisonjo2786** [comment]
Ok cool, not super worried about it anyway -- as long as the title is two
words not one :)
