### ISSUE TITLE
Register/Submit Sessions buttons > Login > user page

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#280]
### Requirements
- [ ] Change register/session button > user login flow: If anonymous user clicks "register"/"submit session", after that user logs, in they should land on ticket/create-session forms, not user/UID.

**IMPORTANT: SEE ALSO** initial attempt results/info over on #277 

###  Initial Research

````
Adam tried this but didn't have time to make it work.

/**
 * Implements hook_form_FORM_ID_alter().
 */
function capitalcamp_glue_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // @todo come up with a more elegant approach here.

  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_capitalcamp_glue_user_register_form_submit';
}

/**
 * Custom submit handler for registration form.
 */
function _capitalcamp_glue_user_register_form_submit($form, FormStateInterface $form_state) {
  // Set redirect to login form.
  $url = \Drupal\Core\Url::fromUri('internal:/form/registration');
  $form_state->setRedirectUrl($url);
}
````

### Background
As anonymous, I clicked Register/Submit Sessions, then logged-in (already have user acct), but then I'm on /user/UID -- I should have been taken to the registration (or session-submission) form.

I was thinking that we could just attach a redirect to the account form so that it takes them to ticket signup immediately

**Comment by alisonjo2786** [comment]
@aweingarten High priority

**Comment by timwood** [comment]
Ack, I've duplicated this by accident in #351

**Comment by timwood** [comment]
This is still an issue.
