### ISSUE TITLE
Fieldset labels look like fields/buttons

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#282]
(Firefox and Chrome on Windows)

The fieldset labels look like something I'm supposed to click on -- like when I got to "sign up for news!" I thought that was like, a button?  I know it sounds silly, but it's styled exactly like the "Register"/submit button at the end of the form.  Anyway, here's what I see:

![image](https://cloud.githubusercontent.com/assets/2660348/25027081/2ca9aec2-2078-11e7-9ddc-7c9f91a457d4.png)

**Comment by charlieartist** [comment]
Am looking at this now. For reference, the above URL is: http://local.capitalcamp.com/form/registration?destination=/user/
What I see happening is the fieldset label styling looks too similar to the buttons and dropdowns, which is indeed confusing. I'll work on restyling this.

**Comment by charlieartist** [comment]
<img width="1268" alt="dgc-289_fixes_20170419" src="https://cloud.githubusercontent.com/assets/3085730/25182665/631f4f88-24e3-11e7-9113-c914830248c6.png">
This has now been modified--visual prominence has been decreased to behave more like a label and less like an interactive element such as a button.

**Comment by alisonjo2786** [comment]
@charlieartist I love this update, screenshot looks wonderful, thank you!

**Comment by aweingarten** [comment]
Looks good closing!
