### ISSUE TITLE
Conf reg: Company Information and Professional Experience: UX improvements needed!

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#283]
It's getting confusing and tedious and frustrating as I continue down the reg form from Company Information to Professional Experience -- the "how do you use Drupal" choices have overlap, the "how would you describe your company" options seem iffy (overlap and gaps at the same time), "select the industries that you work in" is suddenly asking about _**YOU**_ after the preceding fields within the fieldset being about your company... "what is your role" is a messy mix of "what is your role" and "what is your role with regard to Drupal" -- **and it doesn't include a "Site builder" option!!!!!**

IDK prob just need to have someone with UX expertise do a once-over of this part of the reg form.

_[original comment -- for issue originally titled "Options for how_would_you_describe_your_company"]_

Need something for like, non-gov and non "agency/firm/vendor" companies -- like, y'know, a regular company :) or a non-profit, or a university.  And more importantly the concept of "I work for the app owner" so to speak (not a vendor).

Suggest adding...
* Nonprofit organization
* Higher education institution
* Other education organization [or whatever you want to say for "K-12 plus whatever other kinds of schools exist"]
* And maybe "Private company" unless you want to leave "other" for that, but idk, that seems weird, right?

**Comment by alisonjo2786** [comment]
> and it doesn't include a "Site builder" option!!!!!

We should fix this bit like, sooner than later!!  Unless "site builder" went away while I was asleep -- it didn't, did it??  I've always loved the term as being SO drupal... amirite @timwood ??

**Comment by jdearie** [comment]
i think site builder was intended to be captured under: Site Administrator, but i can see how that's confusing. Recommend renaming Site Administrator to Site Builder and add Content Manager as a new field.  Updated #213 to reflect that.

**Comment by jdearie** [comment]
The full list of options identified in #213 included non-profit and a few others. I think we need to bounce all the form fields against what's in #213 to ensure they match.

Here's the list of what should be for company info:

Advertising, Marketing, PR
Agriculture, Forestry, Fishing
Construction
Education
Finance, Insurance, Real Estate
Government
Hospitality, Travel
Manufacturing
Media
Medical, Pharma, Biotech
Nonprofit
Retail or Wholesale Trade
Services
Other

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/297

**Comment by aweingarten** [comment]
Done
