### ISSUE TITLE
Conference registration success msg, "email sent to  ."

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#284]
The success message after the conference registration form says "Thank you for registering, an email is being sent to ." (with a blank at the end, no email address)

![image](https://cloud.githubusercontent.com/assets/2660348/25027452/b5635162-207a-11e7-9afd-31077a8dfd17.png)

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/298

**Comment by aweingarten** [comment]
Fixed
