### ISSUE TITLE
User page: no register/submit sessions buttons

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#285]
(I understand not showing the header/banner/whatever it's called, but we'd still want it to have register/submit session buttons, right?)

**Comment by aweingarten** [comment]
It looks like the buttons are not rendering correctly here:
https://capitalcampdev.prod.acquia-sites.com/user/login?qweqwe

But are on all other pages

**Comment by charlieartist** [comment]
Is this an issue of code not being pushed to dev yet? I just checked to see what's going on, and this is what I'm seeing:
<img width="1338" alt="20170420-govcon17-userloginpage" src="https://cloud.githubusercontent.com/assets/3085730/25243572/7a5542d2-25cb-11e7-8c48-1a00f9587b33.png">

**Comment by alisonjo2786** [comment]
@charlieartist Agreed -- I see them, too, prob was just b/c I submitted this issue a week ago!  Thanks!
