### ISSUE TITLE
Conf reg form: Location info fields

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#286]
* Shouldn't be collecting full address (https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/213)
* Country: Always nice to have "United States" at the top of possible!
* Address fields, including Address 2, are claiming to be required (there are asterisks) but they aren't actually required?

![image](https://cloud.githubusercontent.com/assets/2660348/25027583/c2f00b08-207b-11e7-99e2-18db671a0bb8.png)

**Comment by alisonjo2786** [comment]
Follow-up: Jess and I agreed that we shoudl also remove ZIP, no sense in having it if we already have city/state -- and no sense in having all three, b/c ZIP would tell you city/state, so we should have EITHER city/state OR zip, and there's no reason to have ZIP if we aren't doing a full mailing address :)

**In other words, please remove ZIP field, too!**

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/307

**Comment by alisonjo2786** [comment]
I'll have to look at the config change in the environment, I think -- the code change is just one long line, not super readable -- but, if street address and ZIP are removed, so it only shows city/state (and country), then great!

**Comment by jdearie** [comment]
closing as this issue will be resolved by the related, yet diff issue in #310
