### ISSUE TITLE
Conf reg: Confirmation email isn't what it's prob supposed to be (?)

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#288]
## Requirements
- [x] Include Thanks for registering for Drupal GovCon.  
- [x] Make email appear to come from drupal4gov@gmail.com.   It's under site settings.  (If already fixed there, check webform settings/webform email settings.)
- [x] End of email message: Add something like...
> Next steps: Submit a session! [link]  Add your user photo! [link]  Tell your friends about DGC!  [link]
> 
> [And, do we have a standard sign-off with stuff like "Questions? Contact..." and "Sincerely, The Drupal GovCon Team" ? @jdearie ?]
> 

## Background
It's a generic Webform submission email, doesn't even have webform name in the subject line haha, and the from email is Adam's acquia email address :)

![image](https://cloud.githubusercontent.com/assets/2660348/25027703/c61fd7f8-207c-11e7-94b0-a7bb0307cd2b.png)

**Comment by lkopacz** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/299

**Comment by alisonjo2786** [comment]
@aweingarten The first task is prob done, I just wasn't positive so I didn't check the box -- but I added a third task.

**Comment by alisonjo2786** [comment]
@jdearie Test this with latest code merge stuffs, if you have time?
