### ISSUE TITLE
Fieldset labels sometimes overlap/bleed into fields

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#289]
(seen in Firefox and Chrome on Windows)

I'm seeing this bleeding/overlap on the "which days will you attend" fieldset, but not the "sign up for news" fieldset -- anyways, FYI:

![image](https://cloud.githubusercontent.com/assets/2660348/25027786/4a69ddb0-207d-11e7-8ef5-ba4f4aa43981.png)

**Comment by jdearie** [comment]
same in Safari/Chrome on Mac.

The dark blue fields are overpowering the field labels... it's kinda hard to read.

**Comment by alisonjo2786** [comment]
@charlieartist Maybe can be closed as dupe of #282 ?

**Comment by charlieartist** [comment]
@alisonjo2786 That is the case. I'm closing it up now!
