### ISSUE TITLE
Session Tracks

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#295]
## Technical Requirements
() Update the updatehook that has these taxonomy terms
() Manually update dev.

## Issue:
Ensure session tracks match our new options.  They are listed below and at https://www.drupalgovcon.org/present

Site Building
Front End
Back End
DevOps
Business (Gov, Non-Profit, Commercial)
End Users / Content Management / Project Management
Design/UX
Community

**Comment by aweingarten** [comment]
Mantually updated
