### ISSUE TITLE
Become a Speaker vs Submit a Session in menu

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#296]
Program menu currently contains links to both.  

Submit a Session takes you to the actual form whereas the Become a Speaker page gives you info about becoming a speaker.

Recommend :
1. remove direct link to submit a session from the menu and only have become a speaker. 
2. update become a speaker's first paragraph to announce session submissions opening with a link to the session submission form. 

Updated text - include links to session submission form where appropriate
"If you have a previous presentation you would like to share, or a new idea bubbling for a new presentation, please submit it.  We are looking for sessions on the following topics.  If your idea doesn't quite align with any of these topics, that's fine, go ahead and submit it anyway!"

**Comment by jonraedeke** [comment]
I'm a little confused on this one. At https://www.drupalgovcon.org/, I don't see a "Submit a Session" link. Also, is session submission open now or should I wait to make the content change on the "Become a Speaker" page?

@aweingarten Should create an update hook even if the production site menu is correct or is syncing with the prod DB sufficient?

**Comment by jonraedeke** [comment]
Ah, I see. We just want the update hook to reflect the menu on prod so dev gets in sync. I'm going to assume we want to wait to change the content when announcing the session submission.

**Comment by jonraedeke** [comment]
Adam recommended just editing the update hooks as an additional safe guard.

**Comment by jdearie** [comment]
Not sure if what @jonraedeke did fixed the issue, but all looks good so closing.

background - @jonraedeke i was commenting on what was on Dev at the time as we were getting testing session submission.
