### ISSUE TITLE
Setup User Account Registration (not ticket)

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#30]
## Business Requirements

() As an anonymous user I want to be able to register an account on the site.

**Comment by prynncamm** [comment]
REQUIRED CRITERIA
=============
| Criteria | Why? |
|---|---|
| First Name | Identifier for the attendee |
| Last Name | Sortable identifier for the attendee for check-in |
| Company | Identify who they are representing |
| Email | So we can communicate with them |

OPTIONAL CRITERIA
=============
We usually wait until the post-event survey to ask these questions, but I think we can get a more realistic picture if we ask this up-front. Registration = questions about them. Post Event survey = questions about us.

| Criteria | Why? |
|---|---|
| Please choose the role that best describes you. Choose as many as you like. <ul><li>Developer <li>Management <li>Sales <li> Themer <li> Site Builder <li>Content Manager <li>Designer <li>End User <li>Other | To better understand our audience and target our offerings |
| In what industry do you work? <ul><li>Government <li>Government Contractor <li> Private <li>Nonprofit <li>Education <li>Other | To understand the industries represented. Useful for our sponsors and for our outreach efforts. |
| Why do you want to attend GovCon? Choose as many as you like <ul><li>Learn something new <li>Expand current skills <li>Network <li>Look for a job <li>Sell your product or service <li>Session topics <li>Present a session | So we have an idea of people's expectations going into the event.|
| How many Drupal Camps do you typically attend each year? <ul><li> 1 - GovCon is it <li>2-3 <li>4 or more | This is good information for sponsors to know. If GovCon is it, it's their 1 chance to reach these people in person.|

**Comment by aweingarten** [comment]
@prynncamm to make personalization simpler can we add one section that maps directly to segment?

**Comment by prynncamm** [comment]
@aweingarten Absolutely

**Comment by mikemadison13** [comment]
after chatting with @prynncamm, we are going to setup Vocabularies called Role, Industry, and Motivation to take the options for the above (first 3 only) and make the terms reusable throughout the site.

**Comment by timwood** [comment]
@mikemadison13 Sounds reasonable to use vocabularies. Role will likely apply to session submissions (may be labeled as "track" tho?).

**Comment by timwood** [comment]
@mikemadison13 Comments base on testing PR #92.

- @prynncamm should the Industry facet on registration be single select (radio button) or single select list rather than multi-select?
- Also, @charlieartist suggested we may want to use select list rather than radio/checkboxes. I've used https://www.drupal.org/project/chosen in the past and it's pretty great.

![image](https://cloud.githubusercontent.com/assets/91050/20239461/58310d64-a8ce-11e6-991f-c33866b2638e.png)

Has anyone thought about how user registration will flow/work with event/ticket registration? This was implemented in a really nice way in COD 7.

**Comment by aweingarten** [comment]
@timwood, we'll probably we'll have to work with event/ticket registration on that in dec-jan once Brian's work on ticket is farther along

**Comment by timwood** [comment]
@aweingarten Do we expect to be accepting registrations for user accounts before tickets are made available?

Also, I think we should try to import user accounts from the previous year. Thoughts on that?

**Comment by aweingarten** [comment]
@timwood that's a very good question.  I think thats something we can decide.

**Comment by timwood** [comment]
I just know that in past years / other conferences when I registered for an account I thought I was done. I didn't realize that I also had to register for a ticket.

**Comment by mikemadison13** [comment]
I like the idea of importing the users, but I think that adds enough complexity that we should/could consider opening a new ticket for it.

**Comment by timwood** [comment]
I did that right after I posed my first comment. #94

**Comment by prynncamm** [comment]
I'm leaning toward single select for the industry.

**Comment by dmkelner** [comment]
We definitely want to collect where the user is located so that we can plan for potentially moving the conference in the future. This was discussed at last year's debrief.

**Comment by prynncamm** [comment]
Are we able to add an check-box where registrants can opt-in to share their demographics and email with  our sponsors? Sponsors are willing to pay for such a list but I want to make sure that there is an opt-in mechanism.

**Comment by charlieartist** [comment]
Amy--that sounds like, from a PII and UX standpoint, it should be opt-in. This is also where our privacy policy should be linked. And, on this, is there some type of COC that advertisers agree to regarding user data?

**Comment by prynncamm** [comment]
@charlieartist Absolutely on all of those. I think privacy policy is still on my plate (unless someone else has worked on it. I got behind on Slack messages and gave up trying to catch up :stuck_out_tongue: ) and I'm working on a sponsor agreement for list use. They will HAVE to be CAN-SPAM compliant and I will be seeding the list with several of my and my colleagues email addresses to make sure.

**Comment by mikemadison13** [comment]
i think we will need to be very cautious about what we do with this data, obviously we should get the requirements for the form itself right, but then we also need to consider how that data will be used in views (and to @prynncamm's point the sponsor data dumps) to ensure that the "rules" for how that data is handled is respected. 

i would propose that it is in scope for this task to add the other fields you want to capture, then we should create a related ticket with all the business logic for when / where that stuff appears and how it is used. any thoughts gang?

**Comment by jdearie** [comment]
updated and final user account registration (separate from ticket registration at #213 )

# REQUIRED CRITERIA

| Criteria | Why? |
| --- | --- |
| First Name | Identifier for the attendee |
| Last Name | Sortable identifier for the attendee for check-in |
| Email | So we can communicate with them |

# OPTIONAL CRITERIA
| Criteria | Why? |
| --- | --- |
| Drupal.org Username | Identifier |
| Picture | to help put faces to names; we ask speakers to upload |
| Bio | to help attendees to get to know one another; we ask speakers to complete |
| Company | Identify who they are representing |
| Job Title | Identify how they are representing |

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/220

**Comment by mikemadison13** [comment]
i've setup captcha, recaptcha, and honeypot for this now as well

**Comment by mikemadison13** [comment]
this has been merged and should be on its way to dev.
