### ISSUE TITLE
contact page not avail to anon useres

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#304]
The contact page  "/contact" is not available to anon users.
users get "You are not authorized to access this page."

**Comment by alisonjo2786** [comment]
@jdearie I don't get this problem -- when I go to https://capitalcampdev.prod.acquia-sites.com/contact and I'm not logged-in, I see the contact form.  Do you still have the problem?

**Comment by jdearie** [comment]
nope. not an issue any more. weird. closing.
