### ISSUE TITLE
Site contact form

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#312]
### Requirements
- [x] Contact form "message" field should be a textarea, not single-line text box.
- [x] Preview button does nothing -- the page with the contact form on it just like, reloads, but everything is exactly the same as before I hit the "preview" button.
- [x] Add submission confirmation -- currently, on submit, you're taken to site homepage without so much as a success message :(  Should prob just go to simple confirmation page, i.e.
> Thank you for your message.  Someone from the Drupal GovCon team will be in touch with you soon.  Please add [DGC or D4G email address] to your email contacts to make sure our response reaches you.

- [ ] Verify that after #292 is fixed, any improvements also apply to the required fields on this form.

#### Background
https://capitalcampdev.prod.acquia-sites.com/contact

**Comment by alisonjo2786** [comment]
@aweingarten High priority

**Comment by bheatonf1** [comment]
I'll be taking this on.

**Comment by aweingarten** [comment]
@bheatonf1 this looks good.  I merged the code. but can you apply recaptcha to the webform so that we don't get spammed out of existence.

**Comment by bheatonf1** [comment]
@aweingarten will do.

**Comment by timwood** [comment]
This looks done.
![image](https://cloud.githubusercontent.com/assets/91050/25558318/e28ee6b4-2cf1-11e7-89bf-d937e5f1da65.png)
