### ISSUE TITLE
Lodging menu item only shows up in menu when on Travel page

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#313]
The Lodging node is linked to from the menu as a sub of Travel.
However - the menu link only appears when you are on the Travel page. Any other page does not show Lodging as a drop down menu choice when you hover over Travel.

**Comment by timwood** [comment]
This is due to the Travel menu item not being set to "expanded". @aweingarten I changed this locally and did `drush cex` but no config changes. Guess menu items aren't managed in config or?

**Comment by timwood** [comment]
I've set the Travel menu item as expanded on the production site.
