### ISSUE TITLE
Conf reg (ticket): Food prefs field

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#314]
### Requirements
- [ ] Remove extra "None" field option (currently have "None" and "No restrictions") -- so, from the top, select list options should be "- Select -" (unselected) then "No restrictions" then "Vegetarian" > etc.

Relates to #324 Standardize first select option across the site
_Related: [comment from Jess on other GH issue](#issuecomment-295846397)_

**Comment by alisonjo2786** [comment]
@aweingarten Changing "None" option should be a do-this-week task IMO.

**Comment by aweingarten** [comment]
Verified on dev

**Comment by timwood** [comment]
@alisonjo2786 FYI, I replaced all labels with '- Select -' on required fields.

**Comment by alisonjo2786** [comment]
Faaaabulous thank you! cc @jdearie
