### ISSUE TITLE
Register for a second ticket - 

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#315]
## Technical Requirements
* [x] Update the hero's to say "Tickets" instead of "Register"
* [x] Update the views block on the users page for session submissions to say "Submit another session".  Include a link for the action.
* [x] Update the views block on the users page for ticket registrations to say "Register another ticket for someone else."  Include a link for the action.

## Background
After logging in, I can see my registrations and update a ticket I've already created... but there's no link on the user page to register for another ticket.

I can get there by manually entering the URL or navigating to a page that has the Register button... but there should be a way from the User page to add a new registration.

We have users that often register multiple people.

**Comment by jdearie** [comment]
now that menu has returned, register and submit session buttons are there. 
While the submit session button may be intuitive enough for users to click on when submitting a second session, I'm not so sure it's as clear for registering for another ticket... especially if the user had to create a new user account when the registered for the event...

**Comment by timwood** [comment]
@jdearie What if we changed the wording to "Register Tickets" ? It seems to fit on iPhone 5 up to desktop pretty well.

@charlieartist @jonraedeke @lkopacz @aweingarten Any thoughts on this suggested solution?

![image](https://cloud.githubusercontent.com/assets/91050/25307939/2fb7f7f2-2778-11e7-842f-f5a56b2505b3.png)

![image](https://cloud.githubusercontent.com/assets/91050/25307940/331864fe-2778-11e7-95da-690733941579.png)

**Comment by timwood** [comment]
Or we could add a views header with a sentence, simple link, button, etc. like this:

![image](https://cloud.githubusercontent.com/assets/91050/25308014/dd9f964e-2779-11e7-9275-1d2944ed3430.png)

**Comment by aweingarten** [comment]
@timwood let's do the modify view.  Can you also make the change to the sessions view too!

**Comment by jdearie** [comment]
I agree with @aweingarten on adding "Reserve another ticket for someone else" being the text in the view.

Register Tickets sounds like i need to register a ticket i already got...

**Comment by timwood** [comment]
So @jdearie you want us to replace "Register" with "Tickets" in the hero button/menu?

**Comment by timwood** [comment]
Sorry @jdearie, didn't see the updates to the original ticket text.

**Comment by timwood** [comment]
@jdearie How do you feel about also adding a "No results" text to the ticket registrations view in case a user gets stuck on the user screen?

> Great! You've got an account, but need to [grab a ticket](/form/registration) in order to attend the event!

![image](https://cloud.githubusercontent.com/assets/91050/25309314/ca45a1f6-2797-11e7-8a78-8356e1e0d255.png)

**Comment by timwood** [comment]
> * [ ] Update the hero's to say "Tickets" instead of "Register"

@aweingarten @sarahjean @jonraedeke In order to accomplish this task do I just update all references to the Register hero button in the theme folder? Do I just edit those manually? Do I need to do anything else?

```
✘ timwood@MacBook-Pro:~/Sites/Drupal-GovCon-2017 [master] $ grep -r "Register" docroot/themes/custom/twentyseventeen|grep hero
docroot/themes/custom/twentyseventeen/sass/components/hero/hero.twig:	  <a class="hero__button" href="/form/registration?destination=/user/">Register</a>
docroot/themes/custom/twentyseventeen/sass/components/internalheader/internalheader.twig: <a class="hero__button" href="/form/registration?destination=/user/">Register</a>
docroot/themes/custom/twentyseventeen/styleguide/section-components.html:	  <a class="hero__button" href="/form/registration?destination=/user/">Register</a>
docroot/themes/custom/twentyseventeen/styleguide/section-components.html:	  &lt;a class=&quot;hero__button&quot; href=&quot;/form/registration?destination=/user/&quot;&gt;Register&lt;/a&gt;
docroot/themes/custom/twentyseventeen/styleguide/section-components.html: <a class="hero__button" href="/form/registration?destination=/user/">Register</a>
docroot/themes/custom/twentyseventeen/styleguide/section-components.html: &lt;a class=&quot;hero__button&quot; href=&quot;/form/registration?destination=/user/&quot;&gt;Register&lt;/a&gt;
```

**Comment by jdearie** [comment]
Great idea.

**Comment by aweingarten** [comment]
@timwood all you need is to edit these 2 files
docroot/themes/custom/twentyseventeen/sass/components/hero/hero.twig:	 
docroot/themes/custom/twentyseventeen/sass/components/internalheader/internalheader.twig
