### ISSUE TITLE
Conf reg (ticket) form: Required fields issues

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#318]
## Requirements

- [x] Separate "Yes, I have read and will adhere to the Drupal GovCon Code of Conduct and Media Policy" from the Participation Release field collection
- [x] Ensure "Yes, I have read and will adhere.."  field is required.
- [x] This "Yes, I have read and will adhere" field can be the last field on the page.
- [ ] Add styling for all form field types to indicate required better and highlight missing fields when submitting form.
- [x] Fix bug with hidden checkbox not allowing JS form validation to display.

I believe the other required fields styling issues may be more browser related... some style with red outlines/halos, some show the message - but they all do something.  the random checkbox seemed to be the only real serious issue.

## Background
Required asterisk" for checkbox fields needs to be more obvious _(see also: "Background" > first bullet.)_:
   ![image](https://cloud.githubusercontent.com/assets/2660348/25249917/ad9d7ac2-25e1-11e7-8c43-7581e5888531.png)

- For more background than you could ever want (seriously), see #292, which is superseded by this issue ( #318 ).
- Recommend making "required asterisk" look more conspicuous -- like at the very least, make it red or some contrasting color.
- Also, we're seeing inconsistent treatment of required fields on the Conf reg (ticket) form -- but some/all of these notes are probably applicable sitewide.
   - Below, you'll find details from testing by Alison and Jess :)
- Understand that there's only so much that can be done with mixed browser support for different things, but if the HTML5 messages can't be everywhere, that makes the "required asterisk" and "red halo" even more important to be conspicuous and universal.
   - OR, we wonder if maybe the HTML5 missed-required-field message can be suppressed and instead maybe add a red message box above or below the form for when required fields are missed, i.e. "Please complete all required fields." -- along with more conspicuous asterisks/halos :)
      - (so, not necessarily the more detailed "Experience Level is required" etc. messages that you get on node-create form, just one blanket message...? at least that's what I'm describing, idk if it's a real thing.)

### Alison as authenticated, using Firefox on Windows 7
**When I hit "register" without doing some required fields:**
1. I see a "red halo" around required SELECT LIST fields that I left empty; I see no "red halo" on text box or checkbox fields:
   ![image](https://cloud.githubusercontent.com/assets/2660348/25242395/6c3bfe92-25c7-11e7-9a6b-e620e0f96305.png)

2. I get the "popup"/HTML5 message thing for the topmost/first missed-required-field on the page, but no other ones:
   ![image](https://cloud.githubusercontent.com/assets/2660348/25249123/cb155582-25de-11e7-837d-d4f7bd1ee0d9.png)

3. When I have all required fields filled-in EXCEPT the "Participation release" checkbox, it does show the HTML5 message "please check this box if you want to proceed" but the message is at the top-left of my viewport, not pointing to the proper checkbox field:
   ![image](https://cloud.githubusercontent.com/assets/2660348/25241682/e1595b3c-25c4-11e7-8b38-7c995d0e6c8c.png)

### Jess as authenticated, using Chrome OR Internet Explorer, on Mac & Windows
**When I hit "register" without doing some required fields:**
1. I get the proper "popup"/HTML5 messages for ALL missed-required-fields at once, as depicted in this screenshot from Lindsey:
   ![image](https://cloud.githubusercontent.com/assets/6540866/25111249/c9c39e6a-23b7-11e7-9da3-8a3a1e6be26a.png)

2. I get NO popup/HTML5 message for the "Participation release" checkbox (even when I have all required fields filled-in except this one).
3. Red halos...
   1. **Internet Explorer:** There are "red halos" on select list and and text box type fields, but nothing on checkbox fields.
   2. **Chrome:** No "red halos" on any field types.

**Comment by alisonjo2786** [comment]
@aweingarten high priority

**Comment by timwood** [comment]
I did a little research on this one and it looks like because we are styling away (display: none) the actual checkbox in favor of the fancy checkbox, the webform JS validation can't target the item to display the validation message, resulting in an error in browser console of:
```
An invalid form control with name='yes_i_have_read_and_will_adhere_to_the_drupal_govcon_code_of_con' is not focusable.
```

![image](https://cloud.githubusercontent.com/assets/91050/25314609/6a0e208c-2815-11e7-905f-6aacca1e0bbf.png)

![image](https://cloud.githubusercontent.com/assets/91050/25314610/6d879270-2815-11e7-8cf5-7fc17e91a706.png)

**Comment by timwood** [comment]
Moved field to last item. Need frontend help for the rest of this task.
![image](https://cloud.githubusercontent.com/assets/91050/25314738/92522b22-2817-11e7-9d78-8720cb41af35.png)

**Comment by alisonjo2786** [comment]
Oh I like this, and I kept forgetting to mention that the "policy links" we're super awkward looking, so this fixes that awkwardness, too, yay!
