### ISSUE TITLE
Session submission form: Missed required fields are illegible

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#319]
### Requirements
- [ ] Change styling of missed-required-fields on node forms (session submission) -- see screenshot below.

### Background
The white text on pink background is not readable :)

   ![image](https://cloud.githubusercontent.com/assets/2660348/25250494/c5d249c2-25e3-11e7-991a-8f482c3bdea5.png)

**Comment by alisonjo2786** [comment]
related-ish to #318

**Comment by timwood** [comment]
Anyone want to take this one? @jonraedeke @sarahjean @charlieartist ?

**Comment by mikemadison13** [comment]
@charlieartist it might be worth looking at the new experimental inline form errors (name?) module that I believe is bundled with Drupal core.

**Comment by timwood** [comment]
Experimental core module name is inline_form_errors, currently not required/installed in my local.
```
 Core (Experimental)     Inline Form Errors (inline_form_errors)      Module  Not installed  8.3.1           
```
Looks like this was the original D8 core issue: https://www.drupal.org/node/1493324

**Comment by timwood** [comment]
Oh, and this page lists the current core experimental modules and their status. https://www.drupal.org/core/experimental#versions
