### ISSUE TITLE
Session submission form: Fieldset styling

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#320]
### Requiements
- [ ] Improve node form (session submission) fieldset styling.

### Background
Fieldsets in session submission form are under-emphasized, especially compared to field labels.  Also, in FF there aren't even triangle icons to indicate collapse-functionality.

### 🌟 🌟 CHROME SCREENSHOT

   ![image](https://cloud.githubusercontent.com/assets/2660348/25250610/4f752492-25e4-11e7-8ccc-c2cb15054caa.png)

### 🌟 🌟 FIREFOX SCREENSHOT

   ![image](https://cloud.githubusercontent.com/assets/2660348/25250687/a6159bc4-25e4-11e7-86c2-718f2d393c4a.png)

**Comment by charlieartist** [comment]
@alisonjo2786 This is a serious UX issue. It probably has to do with some of the long class tags that Drupal is famous for. I'll take a look at this.

**Comment by alisonjo2786** [comment]
@charlieartist So I was just going to say, I think a lot of the visual issues I'm seeing are b/c the node-add pages are "meant" to use the admin theme, but auth users dont' have access to the admin theme...?  Maybe it would help as a starting point to tell node-add/edit pages to use site theme instead of admin theme, so it can be a uniform styling task for you...?  Just a thought based on my initial digging :)

**Comment by aweingarten** [comment]
Fixed in prod by checking use admin theme for node pages on appearance settings

**Comment by alisonjo2786** [comment]
@aweingarten It was already using admin theme (at least it was on Dev) for privileged users, but not for auth users, that's why I speculated that auth users didn't have access to admin theme -- I just checked on prod and it looks to still be using the normal site theme (not the admin theme) for my test-auth-user acct for the session submission form -- maybe it's just cached, but I think you'll need to do that permission change for the fix to work (or have you verified as an auth user?).

**Comment by aweingarten** [comment]
@alisonjo2786 I tested this on prod and its working as expected.  we had been messing with that setting on dev to test something else

**Comment by alisonjo2786** [comment]
Ok it wasn't the admin themewhen I checked as an auth user on prod when I
checked before my earlier comment today, unless the admin theme on prod is
different from that of Dev (it looks like the regular sit theme to me), or
unless it's like cached...? I'll reply again with a screenshot when I get
to my hotel.

**Comment by alisonjo2786** [comment]
@aweingarten Maybe I'm just misunderstanding the situation, but I def see "create session" with the twentuseventeen not seven -- and "use admin theme for node editing" is unchecked on prod, unless I'm looking wrong.  Screenshots attached, checked as auth and as admin.

![screenshot_20170423-201740](https://cloud.githubusercontent.com/assets/2660348/25318720/8b7f9df2-2862-11e7-8f24-5b34fb435756.png)
![screenshot_20170423-201927](https://cloud.githubusercontent.com/assets/2660348/25318719/8b7f90dc-2862-11e7-8e1c-1e7613c0dde4.png)

**Comment by aweingarten** [comment]
Okay I was looking at registration not session.  It looks like the SASS needs to be updated and made more generic

**Comment by alisonjo2786** [comment]
Ahhh ok, cool. I'll reassign to Karl for now!
