### ISSUE TITLE
Session submission: File fields...

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#321]
- [x] Change _Slides_ field label to "Supporting Documents"
- [x] Update _Supporting Documents_ help text to say "Upload your presentation and/or any files referenced in your session.  You may also link to slides, code repos, or other external resources in the Description field."
- [x] Supporting Documents field should allow the following file type uploads: PDF, PPT, PPTX, key, odp, otp, and .odg
- [x] Remove Image field.

**Comment by alisonjo2786** [comment]
@aweingarten high priority

**Comment by bheatonf1** [comment]
I will be taking this on.

**Comment by bheatonf1** [comment]
I'm equally unclear on the intent of the 'image' field. I have removed it. I have added a 'link' field for the presentation as ppt, pdf is now becoming eclipsed by web hosted decks. I've added a group to encompass both filed and link submitted slides.

**Comment by charlieartist** [comment]
@bheatonf1 Sounds good to me. On conference sites I've built in Drupal, the HTML link is all we offered, since many seasoned presenters already post their decks online.

**Comment by jdearie** [comment]
agreed that we can lose the image field. not sure why it's there.

While the link field is nice, I find that there's inconsistency in it's use. Some will link from the body, some the link field, some both, and some none.  Not sure how much value there is in it, but not a deal breaker for me to have it.

As for file upload - I do think we need to keep it.  I would like to allow for PDF, PPT, PPTX, key, odp, otp, and .odg.  

Some speakers use the file upload to upload supporting docs as well - not just slides, so PDF is useful.

Maybe consider renaming the slides label to "Supporting Documentation" or similar.

**Comment by alisonjo2786** [comment]
@jdearie Ooo I like that label idea!

All I'll add for now is that I think we should just add to the help text something like, "You may also link to slides, code repos, or other external resources in the Description field."

I know it's like, "duh," but way too often I think ppl forget to do it, and this just might help.

**Comment by alisonjo2786** [comment]
@aweingarten @jdearie Do you know if there are any circumstances where auth users will need to use the "file browser"?  I removed the task checkbox from this task b/c the Image field "file browser" permissions problem is no longer relevant, but do we need to add it as a separate issue, or will auth users never need to use the File browser dialog?

_Here's what I removed from this GH issue description:_
[checkbox] Image field: File browser dialog: Access denied for authenticated user:
   ![image](https://cloud.githubusercontent.com/assets/2660348/25251005/d18f9e48-25e5-11e7-8147-5b8573cf866c.png)

**Comment by bheatonf1** [comment]
I will wrap this up this evening.

**Comment by alisonjo2786** [comment]
I think maybe the perms issue might have been fixed, but I'm not positive.....?

( @bheatonf1 ?)

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/381
