### ISSUE TITLE
Rich text editor permissions

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#322]
### Requirements
- [ ] Give authenticated role access to rich text editor / text format -- and/or add new (more restrictive) text format for authenticated users).

### Background
Session "description" field is plain text only, and it's like tiny text box, when I'm an auth user -- but it's a normal WYSIWYG field when I'm admin user.  
   ![image](https://cloud.githubusercontent.com/assets/2660348/25251408/46675c46-25e7-11e7-9861-7972f2da25cc.png)

--not sure what @alisonjo2786 was using, but works for me;
Logged in as auth user
In Chrome on Mac, Safari on Mac, Chrome on Win7, IE on Win 7, FF on Win 7:
- no option to select a text editor, but a few simple styling options are there
![image](https://cloud.githubusercontent.com/assets/5174534/25255294/bfdebaf0-25f7-11e7-925c-09a2c9af288e.png)

**Comment by alisonjo2786** [comment]
@aweingarten high priority

**Comment by bheatonf1** [comment]
I will be taking this on

**Comment by aweingarten** [comment]
Done
