### ISSUE TITLE
Standardize first select option across the site

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#324]
- [ ] the first field of a select option needs to be consistent across the site.  Set all visible select options to "-Select-"

**background**
we have different values for the first select option across the site. Some say -Select- 
some say -Select a Value- and some say -None-

**Comment by charlieartist** [comment]
@jdearie This ties into a discussion @aweingarten and I were having about the classes that wrap these elements. When some structural changes were introduced to form elements, some previous styling was broken, and I had to redo it. I'll check what we can do to remedy this.

**Comment by timwood** [comment]
To change this, will require a code-based (or module?) solution as there doesn't appear to be a way to change the default on content type fields, like there is on Webform.

**Comment by timwood** [comment]
This is low priority.

**Comment by timwood** [comment]
@jdearie We now have "- Select -" on ticket registration form and " - Select a Value -" on Session form (and presumably other node types). Does this seem consistent enough? It's not a simple site builder task to change the default on node form(s).

Can we cancel this task?

**Comment by jdearie** [comment]
works for me...
