### ISSUE TITLE
Session Submissions Need Co-presenter's field

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#333]
* [ ] Configure existing Session content type to add user reference field labeled Co-presenter?
* [ ] Configure display of the field (style if necessary)
* [ ] Export config via CMI

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/341

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/436

**Comment by mikemadison13** [comment]
@lkopacz do you have availability to help with some styling on this?
