### ISSUE TITLE
Change basic site settings email address to not be Adam's email

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#335]
Email from the site, including registration confirmation email, arrive with a From header of Adam's email, because his email is the site email. @aweingarten

**Comment by timwood** [comment]
@jdearie Do you think this From email address should be drupal4gov@gmail.com or info@drupal4gov.us?

**Comment by jdearie** [comment]
Good catch. It should be info@drupal4gov.us
