### ISSUE TITLE
Center Call To Action Buttons on secondary pages

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#342]
## Technical Requirements
* [ ] Center the call to action buttons.  So that they are consistent with the homepage. 
* [ ] If possible ensure that the hero stretches edge to edge even at extreme widths

<img width="1564" alt="screen shot 2017-04-23 at 3 45 23 pm" src="https://cloud.githubusercontent.com/assets/6517820/25316868/f9b45208-283b-11e7-9008-e5a212934b34.png">

**Comment by timwood** [comment]
> Center the call to action buttons. So that they are consistent with the homepage.

Isn't the hero area vertically shorter (intentionally) on sub-pages so it's not always in the way? On desktop there is space for them to be off to the side, probably why they are up there.

**Comment by aweingarten** [comment]
It is shorter, but the mobile behavior does this perfectly centered.  There is enough space.  The current desktop behavior seems confusing and looks like a bug. I

f that's a call to action it should be in their faces otherwise we should remove the buttons and rely on the menu?

**Comment by charlieartist** [comment]
@aweingarten @timwood Something looks very broken in that display above.
