### ISSUE TITLE
Remove Checkbox Styling

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#349]
## Background
The checkboxes are breaking validation remove the styling

**Comment by timwood** [comment]
Related to #318.

**Comment by charlieartist** [comment]
No way to deal with this?

**Comment by charlieartist** [comment]
@aweingarten  I can do a quick test--things are slow here today.

**Comment by jonraedeke** [comment]
Relevant validation error https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/318#issuecomment-296450125

**Comment by jonraedeke** [comment]
@charlieartist  We need to be able to tab through the checkboxes for accessibility. So I will go ahead remove the styling until we can figure out how to get the form to validate and tab through with the styling.

**Comment by charlieartist** [comment]
@jonraedeke OK. How can I test for this and move forward in the meantime?

**Comment by jonraedeke** [comment]
@charlieartist Thanks. Log in locally, click the "Ticket" link in the hero and fill out the form except for the last checkbox. You might try hiding the checkbox offscreen or clipping it instead of display:none. Also, make sure it gets highlighted on focus with the tab key.

**Comment by charlieartist** [comment]
@jonraedeke OK. I created another ticket to deal with this: [352](https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/352)

**Comment by aweingarten** [comment]
Validated on DEV closing!
