### ISSUE TITLE
Redirect new user from Drupal account registration to Ticket registration form

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#351]
* [x] When a user successfully creates a new Drupal account at /user/register, redirect them to /form/registration to complete the Conference ticket registration

**Comment by timwood** [comment]
Possible solutions:

- Add a hook on successful /user/register form submission to redirect to /form/registration (the ticket registration webform)
 - Optionally fill in fields from Drupal user account registration details
 - Optionally add a note/message to the top of the ticket registration webform explaining why the user is filling out another form
- Change the "Ticket" link url to use /user/register?destination=form/registration which will take an anonymous user through the account and ticket registration process automatically without any hooks.
 - ~~Optionally set the ticket registration webform to redirect the user to /user~~ the webform already does this!

![image](https://cloud.githubusercontent.com/assets/91050/25350636/c46137e8-28f3-11e7-96fd-2c53a3aa30f8.png)

**Comment by timwood** [comment]
@bheatonf1 Please implement the redirect hook option per @aweingarten . His initial research and code is available in #280

**Comment by bheatonf1** [comment]
Ok @timwood. I've got something working locally. Wish push a PR shortly.

**Comment by timwood** [comment]
Done!

**Comment by bheatonf1** [comment]
@timwood does this take care of issues in #280?

**Comment by timwood** [comment]
No, unfortunately not. After re-reading #280 I realized that issue is talking about a different workflow.
