### ISSUE TITLE
Style proposed sessions view and individual session node page

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#354]
With #273 merged we now need to make the proposed sessions view look pretty.

* [x] Style sessions view output to look pretty (including the footer as a generic item that can be reused)
* [x] As needed, modify/enhance sessions view output
* [ ] Style session node page

**Comment by mikemadison13** [comment]
i would suggest looking at DrupalCon's sessions page (or our own from last year) as a basis for this.

@bendygirl and @jdearie would like this LIVE by 5/20 so it needs to be done ASAP.

**Comment by jdearie** [comment]
All page views of sessions (regardless of proposed vs accepted etc) need to show the session speaker.  I'll update actual issue text with fields we need to show.

**Comment by charlieartist** [comment]
I see there are duplicates.

**Comment by mikemadison13** [comment]
styling should also apply to https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/392

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/381

**Comment by jdearie** [comment]
think this is done. closing
