### ISSUE TITLE
User Registration Captcha Requirement Very Easy to Miss

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#356]
I almost missed the captcha requirement... it's the last field (after a bunch on non-required fields) and the label is very easy to miss.

![image](https://cloud.githubusercontent.com/assets/5174534/25388921/20bac35c-299d-11e7-9c02-479f29aa1acc.png)

**Comment by timwood** [comment]
I think in production it uses recaptcha do easier to see.

**Comment by timwood** [comment]
Scratch that. We have no captcha on production ATM. This is not good.
