### ISSUE TITLE
Update header text on Ticket Registration Page

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#359]
Replace this basic header text: 
"Registration successful. You are now logged in."

With:

"WAIT - YOU STILL NEED A TICKET.  Now that you are registered on the site, you can get tickets to Drupal GovCon for yourself and others.  Please complete this ticket registration form for each person that needs a ticket to the event."

**Comment by bheatonf1** [comment]
[PR submitted](https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/404)

**Comment by jdearie** [comment]
pretty sure this is done.
