### ISSUE TITLE
Sponsor logos on sponsor page should link to their link

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#363]
Right now the sponsor logos just link to the /sponsors page.

They should link to the url we capture in the sponsor content node.

**Comment by dmkelner** [comment]
This is still not working correctly. Still link to /sponsors.

**Comment by timwood** [comment]
@mikemadison13 Can you undo what you did in https://github.com/Drupal4Gov/Drupal-GovCon-2017/commit/8bc1458611716f3e262a75ddf79826b0434df803#diff-9160d7b2f882ba7ca190f0c6664a6d33 to get close this issue again?

**Comment by jdearie** [comment]
working now so closing.
