### ISSUE TITLE
Auth users need to be able to create a BoF

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#364]
Users with accounts registered on the site need to be able to create BoFs.  Could be as simple as a content type, but we will need to consider how we make sure there are spaces for all the BoFs.

If we aren't doing session scheduling on the site, how do we get BoFs scheduled?  
While we can identify where BoFs can be (rooms) and when (day/time) - how do we ensure spaces don't get double booked?

**Comment by bheatonf1** [comment]
@aweingarten @mikemadison13 any thoughts on implementation here? I'm happy to create something but don't want to venture into the wrong direction.

**Comment by timwood** [comment]
This should probably happen over in [drupal-cod](https://github.com/drupal-cod) as a sub-module of [program](https://github.com/drupal-cod/program), like session is, but I defer to @aweingarten, @mikemadison13 or @japerry. I know the COD team was architecting/planning via Google docs or other somewhere...

**Comment by mikemadison13** [comment]
yeah, my thoughts would be a drupal-cod/program submodule for bofs (that would sit along side sessions). we can talk about it on the COD scrum today

**Comment by bendygirl** [comment]
Just wanted to make sure folks know that only time frame we'd have in the schedule for BoFs would be lunch. And only room available for use would be a room not assigned a training. That's Room E. 

I don't think for this year this is a priority. I'm labeling this low priority for now.
