### ISSUE TITLE
Fix "Media Policy" link on ticket registration

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#369]
<img width="351" alt="screen shot 2017-04-27 at 10 21 40 pm" src="https://cloud.githubusercontent.com/assets/91050/25511904/13f14a04-2b98-11e7-8b2c-f9ed1f9f5739.png">

Right now it links to "#".

**Comment by jdearie** [comment]
https://www.drupalgovcon.org/media-policy

**Comment by timwood** [comment]
Thanks for the link @jdearie. Once the PR is checked and merged, this will be available on Dev.

**Comment by timwood** [comment]
@mikemadison13 This was also lost in https://github.com/Drupal4Gov/Drupal-GovCon-2017/commit/8bc1458611716f3e262a75ddf79826b0434df803#diff-6385350be8e3cebaae61baf8d8a43fd8
