### ISSUE TITLE
Install an XML Sitemap

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#37]
## Business Requirements

(/) As a site maintainer I want my site to be easily indexed by search engines

**Comment by aweingarten** [comment]
Deployed and confirmed working

**Comment by mikemadison13** [comment]
there is a bug in this module that is preventing a lot of things from happening properly. when the module is installed manually or via drush, all is well. however when installed via CMI, then the module is missing database tables which cause fatal errors.
