### ISSUE TITLE
Remove/replace sentence about registration and speaker submissions on home page under "Stay in the loop"

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#370]
It currently reads:
> Registration and speaker submissions to be coming soon.

<img width="977" alt="screen shot 2017-04-27 at 10 26 51 pm" src="https://cloud.githubusercontent.com/assets/91050/25512016/bcfc9f54-2b98-11e7-8a70-450bfa0077b9.png">

**Comment by timwood** [comment]
I couldn't figure out where to make this edit.

**Comment by jdearie** [comment]
This isn't content I created either... and I'm not sure where to edit it. @charlieartist do you know?

**Comment by charlieartist** [comment]
@jdearie Yes--on the original site launch, when content types weren't fully baked, the initial content was styled and placed in custom blocks. @sarahjean was looking at doing custom fields to deal with homepage content, but I'm not sure as if this was ever completed.

**Comment by jdearie** [comment]
that's what i thought... i looked at blocks, but i don't see one that matches what's on the home page. there is a home page content block (block/31), but it has different content than what is currently being displayed.   (unless someone literally just updated it)

**Comment by charlieartist** [comment]
@jdearie It probably would be good to check with @aweingarten. Initially, I had static HTML/CSS that could have been posted, but that content got cut up and put into the the D8 build as a component. Now, it's possible that this can be updated through the style guide. I can check on that. What is the copy change?

**Comment by timwood** [comment]
Thanks for the tip, Karl. Looks like it's in three places in the code: https://github.com/Drupal4Gov/Drupal-GovCon-2017/search?utf8=%E2%9C%93&q=%22Registration+and+speaker+submissions+to+be+coming+soon%22&type=

**Comment by charlieartist** [comment]
@timwood Sure--this would be good to resolve. I know the initial construct was quite puzzling. This content, as I originally envisioned, cold all be controlled by CSS classes, requiring no custom fields or content types.

**Comment by jdearie** [comment]
I think we can get away with just removing the Registration and speaker submissions coming soon sentence.

**Comment by charlieartist** [comment]
@jdearie OK. I'll do a branch, PR, and ping @aweingarten on making this happen.

**Comment by timwood** [comment]
@charlieartist I'm handling this today.
