### ISSUE TITLE
Recaptcha site key and secret key lost on new deployment to prod

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#372]
We've put the Recaptcha site and secret key (from the D4G Gmail account's recaptcha registration) into the live site via Drupal admin interface, but it gets removed when code is deployed to the site. I believe this is due to null values for these settings being included in exported config [blob/master/config/default/recaptcha.settings.yml](https://github.com/Drupal4Gov/Drupal-GovCon-2017/blob/master/config/default/recaptcha.settings.yml).

Can we reliably remove the two lines from the config without it being re-exported by a team member in the future?

**Comment by mikemadison13** [comment]
@timwood this should be addressed now.

**Comment by timwood** [comment]
Great. Thanks!
