### ISSUE TITLE
Tickets view/report (ASAP re: volunteers)

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#378]
## Requirements
- [ ] (short-term / ASAP) Report of ppl interested in volunteering (needed by Nneka).
   - so, super simple view that can be extended later, or a "one-off-in-prod" temp view to be replaced as soon as we've created a "real" one.

### Background
Nneka needs to start reaching out to people this week (5/1/2017) -- per messages on Slack, starting with [this one](https://drupalgovcon.slack.com/archives/C081SGC7N/p1493667960577320).

**Comment by timwood** [comment]
After the conversation on slack regarding using webform results reporting and exporting, should we just close this issue?

**Comment by alisonjo2786** [comment]
Yep -- was just coming on to do that, was waiting for her to verify, and I guess her "reaction" on my comment is the answer :)

#### As @timwood says, Nneka is fine for the immediate term using the webform results "download" functionality.
