### ISSUE TITLE
Display top 3 news articles on home page

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2017#384]
Prefer it be named News & Updates (or similar)
This block is for content that editors can use to coordinate with mailchimp and social media pushes.

We need a block here to promote closing dates for room blocks, keynotes, announcements, links to web forms when recruiting volunteers.

Thinking right sidebar, but leave that up to the designers!

Add a link to "more news" that points to page created in #398

**Comment by charlieartist** [comment]
New content type created, as well as critical alerts. Here are images of special announcements, and critical alerts:
<img width="641" alt="20170609-govcon17-homepage_001-mobile" src="https://user-images.githubusercontent.com/3085730/26989655-e6de7a86-4d21-11e7-8262-25ff710dc935.png">
<img width="1600" alt="20170609-govcon17-homepage_003-desktop" src="https://user-images.githubusercontent.com/3085730/26989711-0fe2af56-4d22-11e7-93e6-563d59397b95.png">

**Comment by mikemadison13** [comment]
added in https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/435
