### ISSUE TITLE
Front Page: Add content for SESSION submission closing

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2017#385]
We need to add to the front page:

Session Submissions CLOSE May 22nd! Submit your session TODAY!

**Comment by jdearie** [comment]
completing issues in the news and announcements milestone would solve this issue.

**Comment by sarahjean** [comment]
PR here to fix block behavior in panels https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/406

**Comment by mikemadison13** [comment]
this has been done temporarily with a custom block on the homepage.

**Comment by charlieartist** [comment]
This is being taken care of in 405.
