### ISSUE TITLE
Create News Article Content type

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#388]
Create a news article content type that can be used to display news and announcements on the home page.

- [x] title
- [x] body
- [x] wysiwyg (for editors to add basic formatting like links, bold or headers to break up content)
- [ ] limited to 5 lines of summary to the front page
- [ ] limited to 3 news items on front page
- [ ] page of all news items linked to on the front page

similar to front page: https://events.drupal.org/baltimore2017
and paged items: https://events.drupal.org/baltimore2017/news

**Comment by mikemadison13** [comment]
@jdearie / @bendygirl can you please provide the desired fields and functionality for this content type?

**Comment by mikemadison13** [comment]
partially done in https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/435

**Comment by charlieartist** [comment]
This was covered in [issue 384](https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/384)
