### ISSUE TITLE
Webform for Scholarship Submission

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2017#390]
Create a webform for scholarship applicants. This needs to provide a download for export to excel or google docs for the scholarship reviewers to determine who to give scholarships to.

Content for WebForm:

The Drupal GovCon Scholarship Program provides travel funds for this year's Drupal GovCon event.

Attendance at Drupal GovCon benefits the scholarship recipient not only by offsetting a portion of the travel expenses, but also by providing an authentic Drupal GovCon experience and connection to the larger Drupal community.  Benefits of attending include networking, learning how to hold local events, training sprints, contributing to drupal core or contributed modules, training, and learning more about the Drupal project.

Recipients will be selected based on their interest, active contribution to the Drupal community, dedication to growing Drupal through code, community leadership, mentoring, and also personal financial need. Additionally, recipients will be expected to volunteer for the equivalent of one half day during the event.

This scholarship application is not available to members of the Drupal GovCon planning committee.  Applications will be accepted until 11:59 pm EDT on June 2nd, 2017.

Webform

- [ ] First Name [text field] [required]

- [ ] Last Name [text field] [required]

- [ ] Drupal.Org User Name [text field]

- [ ] Employer [text field] [required]

- [ ] Job Title [text field] [required]

- [ ] Phone Number [text field]

- [ ] Email [text field] [required]

- [ ] Where will you be traveling from? [text field] [required]

- [ ] Provide link to your resume, LinkedIn profile, and/or other professional summary [text field]

- [ ] Why is it  important to you to attend Drupal GovCon? [At least 500 characters text field] [required]

- [ ] My employer is not paying for any expenses related to Drupal GovCon [check box] [required]

- [ ] I am not a member of the Drupal GovCon planning committee.	[check box] [required]

- [ ] Estimate for travel expenses	 [text field] [required]

**Comment by jdearie** [comment]
too late for 2017 - need for next year.
