### ISSUE TITLE
Proposed Sessions Page/View - needed BEFORE May 20

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2017#391]
Users need to see a list of all proposed sessions. This helps increase number and quality of sessions submitted.

I've heard this is in Dev but needs styling. Needed ASAP.

**Comment by mikemadison13** [comment]
@bendygirl there IS a propopsed session view (https://www.drupalgovcon.org/program/proposed-sessions) but it isn't linked up, and it needs some TLC on the styling side. I would propose we hand this off to @lkopacz  / @charlieartist  / @jonraedeke  for some work. any takers?

**Comment by mikemadison13** [comment]
specifically (what I see):

- [ ] style the footer (should be a general styling to apply to all footers)
- [ ] style the general layout of the sessions to be more in-line with what we have seen on drupalcon's site https://events.drupal.org/baltimore2017/sessions/accepted

**Comment by mikemadison13** [comment]
this is a dup of https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/354
