### ISSUE TITLE
Accepted Sessions

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2017#392]
View for all accepted sessions

**Comment by charlieartist** [comment]
I'll take on styling this.

**Comment by mikemadison13** [comment]
this should just be a new display inside the same view, filtered on the accepted taxonomy term

**Comment by bheatonf1** [comment]
For accepted sessions - use current view and make a new display on the same view

**Comment by jdearie** [comment]
overtaken by new issue #419

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/381
