### ISSUE TITLE
Listing of Attendees

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2017#394]
Need a list of ticketed attendees to display to anon user

Page/View should include the following fields from the ticket registration:

First Name
Last Name
Company Name (see #397)

AND where the "Show on attendee listing page" checkbox was checked.

Admins should have a view/page(s) where they can view all the data submitted during ticket registration.

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/401
