### ISSUE TITLE
News Page

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#398]
create a news article page/view that displays a listing of all news articles.  only top 3 would be on home page. 

List should be of the content type in issue #388

**Comment by charlieartist** [comment]
@jdearie Now that the homepage announcements are going to be deployed, I could create another view display off this, with unlimited numbers of announcements, and no expiration, as content does on the homepage.

**Comment by charlieartist** [comment]
This can be based off [issue 384](https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/384)
