### ISSUE TITLE
Make intro block (block--dgc--intro) on homepage editable

### ISSUE THREAD

**Issue by sarahjean** [Drupal4Gov/Drupal-GovCon-2017#405]
Talked over a few options on scrum, we can either set this up as a fielded block plugin (or custom block type?) or we could set up Ckeditor so there's access to apply some classes (like for the intro).

**Comment by charlieartist** [comment]
@sarahjean Know we had discussed this a while ago, then tabled. IIRC, we had looked at creating multiple fields to control input styling. Aside from that, should we look at a space in the main content area where expiring blocks/banners could be placed? This is how I deal with similar issues on some client sites. Perhaps it would be good to look at what content would be changing.

**Comment by charlieartist** [comment]
A quick fix would be creating a custom block/view display for content that can be set to auto-expire. This is a pattern I employ on projects where content editing can be a challenge--which helps keep outdated content off the site.

**Comment by charlieartist** [comment]
Due to config export issues, this is being moved to issue #413.
