### ISSUE TITLE
UX: Become a Speaker and "Present" Block -  inconsistent naming 

### ISSUE THREAD

**Issue by lkopacz** [Drupal4Gov/Drupal-GovCon-2017#410]
It's "Become a Speaker" in the nav, and "Present" in the block on the homepage, which makes it frustrating as a user.

**Comment by jdearie** [comment]
good catch  i wasn't even thinking about the block on the home page when i created the "Become a Speaker" page. I was just copying DrupalCons IA.

Same issue with "Connect" block and "Sponsor" in the menu... though in this case, I'm not sure how many people would see Connect as sponsorship.

Do you think it's worth the effort to change now?  Would we confuse users by changing the text in the menu? I would expect more people are used to seeing the text in the menu than blocks on the home page... so maybe we should change the text in the blocks?  

I want to take a look at our analytics... to see if anyone is using the blocks on the home page. I don't even see them when I go to the site on my laptop... or even my PC at work.
