### ISSUE TITLE
change ticket registration email

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#412]
update email text to remove request to submit a session.  new text should be:

You've been registered for Drupal GovCon 2017 and have secured a ticket to the event.

Next steps: Tell your friends about Drupal GovCon!

username: [username]
password: your password

Change your mind about getting email alerts?  Subscribe to our e-mail list:
http://eepurl.com/bbJASn

Follow us on social media:
https://twitter.com/drupalgovcon
https://www.facebook.com/DrupalGovCon

-- Drupal GovCon team

**Comment by bheatonf1** [comment]
[PR](https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/415)
