### ISSUE TITLE
Add Special Announcements

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/Drupal-GovCon-2017#413]
This supersedes issue 405. The main purpose is to create a content type and view display on the homepage for special announcements.

**Comment by bheatonf1** [comment]
@sarahjean @timwood I can't recall how this differentiates from the 'News' content type. Are we creating yet another content type for this? Of should this be a block? I'm happy to take this on. @charlieartist were you able to create the news content type mentioned in https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/388 ?

**Comment by mikemadison13** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/435
