### ISSUE TITLE
add date/time and room fields and create schedule views

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#419]
while we won't be doing any actual plotting-type scheduling, we would like to have some kind of dynamic schedule options for our attendees.

- [x] add a date/time field to session content type

- [x] add a text field for Room (we won't do drop-downs in case we end up getting access to rooms we don't currently have booked)

- [x] create a view that shows the schedule; view should include session title and presenter, track, date/time field, and room field. session title should link to the session node and presenter should link to the user page.  

- [x] schedule view should also include an exposed filter that will allow users to filter by track, by title (autocomplete?), by speaker, and by room.

**Comment by mikemadison13** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/426 partially addresses this ticket.

**Comment by jdearie** [comment]
pulled out my schedule to #492. we can close this now.
