### ISSUE TITLE
users need to be able to delete tickets

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#421]
users need to be able to delete tickets.  

unless i'm missing something, i don't see a way for a user to delete their ticket... only update the info and save.

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/426

**Comment by jdearie** [comment]
re-opening because:
delete webform option is there... i get access denied after confirming that i wanted to delete (attempting to delete my own submission when logged in as sampleuser)
