### ISSUE TITLE
non-session events

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#429]
we need to be able to display non-session events on the schedule.  We will use this to add things like keynotes, breaks, lunch, registration etc to the schedule

perhaps a new content type?
required fields would be:

Field Label | Field Type
------------ | -------------
Title | Text
Date/Time | date/time
Room | Text

See last year's example: https://www.drupalgovcon.org/drupal-govcon-2016/schedule.html

**Comment by charlieartist** [comment]
I'll check on the site/node architecture. Ideally, there'd be a way to do this easily, in a way that automatically is displayed in the program, just like session events.

**Comment by charlieartist** [comment]
@jdearie I'm working on creating the view for the program/schedule, will see on how to add this in. Perhaps, also an exposed filter to allow users to show these without speaker sessions.

**Comment by charlieartist** [comment]
I'm in the process of creating this content type in order to display it correctly in the program in [issue 440](https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/440)
