### ISSUE TITLE
Allow sponsors to have more than one sponsorship level

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#430]
The sponsorship level in the sponsor content type only allows for one type of sponsorship level. Some sponsors are doing both (i.e. core and training). To have them show up properly on the sponsorship page, I have to add them more than once - one for each level.

**Comment by mikemadison13** [comment]
@krapp91 the config change looks great on this, the multi-select field not so much (if you go into edit an existing sponsor in your local you can see what it looks like). i would advise a second commit that adds a bit of styling. @lkopacz / @charlieartist would be good resources for that if you have questions
