### ISSUE TITLE
Roles Summary

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#432]
While many content types have status/moderation... we don't have enough volunteers to create the need for content reviewers vs creators.  

Summary of roles and associated permissions. 

**Volunteer Role**
- View ticket webform results
- Edit ticket webform submissions

**Sponsor Role**
- Add/Update/Delete Sponsor content type

**Editor Role**
- Add/Update/Delete Sponsor content type
- Add/Update/Delete News content type
- Add/Update/Delete Session content type
- Add/Update/Delete Basic page content type

**Authenticated Users**
- Add/Update/Delete OWN Ticket webform submission
- Add/Update/Delete OWN Session content type

**Comment by bheatonf1** [comment]
@jdearie is this ticket to confirm these permissions or are we revising the current permissions per this list?

**Comment by jdearie** [comment]
i believe the intent was to revise the current permissions - or at least add the roles we don't already have.

Volunteer role has priority.  We can make do without the editor and sponsor roles until 2018... but volunteers need access to the webform results during the conference to check people in.
