### ISSUE TITLE
Update BLT To Resolve Drush Alias Issue

### ISSUE THREAD

**Issue by mikemadison13** [Drupal4Gov/Drupal-GovCon-2017#44]
See https://github.com/acquia/blt/pull/593 at the BLT issue.

This is causing Drush to fail on remote aliases unless you do a drush --include=drush in the commands.

**Comment by mikemadison13** [comment]
I think with the most current version of BLT these are now working properly. Could others please try @capitalcamp.dev status and ensure it is working properly for them?

**Comment by aweingarten** [comment]
works for me.  Closing.
