### ISSUE TITLE
Revise User Flagged Session Block

### ISSUE THREAD

**Issue by brooke-heaton** [Drupal4Gov/Drupal-GovCon-2017#476]
The block is currently showing on any users page - add contextual filter for the current user id. This has been done o Prod - need to export config.

**Comment by bheatonf1** [comment]
Not sure if this is still an issue. Could not reproduce. Sorry that I didn't add more details - it was a late one :(

**Comment by bheatonf1** [comment]
Yep this is still an issue noted by @jdearie I have resolved on Prod. This needs to be committed in code.
