### ISSUE TITLE
Improve User Display

### ISSUE THREAD

**Issue by brooke-heaton** [Drupal4Gov/Drupal-GovCon-2017#477]
Currently only the user name displays - we should show First Name, Last Name, Bio etc - we may need a Twig tpl for this. 

- [x] First Name
- [x] Last Name
- [x] Organization
- [ ] Drupal.org username
- [ ] Make user url include the user name /username

**Comment by charlieartist** [comment]
@bheatonf1 I have bandwidth, and need to get better at D8 templates. Should we touch base?

**Comment by bheatonf1** [comment]
@charlieartist yea, this might be an ideal one for you - I think we just need a better Twig template, but there might be more too it.

**Comment by charlieartist** [comment]
OK--I have an annotated wireframe here. LMK if there anything I have missed as far as content.
![1880-govcon17_wireframe-01-mobile_userprofile_v01](https://user-images.githubusercontent.com/3085730/27595801-ab5ff990-5b2b-11e7-8e6b-8ec0a0d462a9.png)

**Comment by bheatonf1** [comment]
@charlieartist is this all now complete? If not, can we add a new issue for remaining tasks and close this out?

**Comment by charlieartist** [comment]
@bheatonf1 I'm working on the view displays to this, as well. Based on feedback from @jdearie, I don't need a separate boolean for public display of user information in the user edit form, since this is covered in the ticket. How should I best link this?

**Comment by mikemadison13** [comment]
see https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/541
