### ISSUE TITLE
Sponsors Link not visible in main navigation

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/Drupal-GovCon-2017#478]
While the level 1 site navigation link Sponsors displays fine on desktop, it isn't visible on mobile, which could be a serious complaint from our sponsors. Will need to be remedied so this link displays at all breakpoints.

Attached are screen grabs to show this:
**Desktop (Works)**
![govcon-sponsorlink-desktop](https://user-images.githubusercontent.com/3085730/27587837-efe60bda-5b13-11e7-9b65-aa0899f405d6.png)
**Mobile (Does Not)**
![govcon-sponsorlink-mobile](https://user-images.githubusercontent.com/3085730/27587869-15a52162-5b14-11e7-96e3-bc70fdeda1be.PNG)

**Comment by bheatonf1** [comment]
Below is the current Prod configuration of the menu. @charlieartist any idea what is causing it to get cut off?
![govconmainnav](https://user-images.githubusercontent.com/19474864/27597305-fadc95b0-5b2f-11e7-84bd-e82ad2ed4cb6.png)

**Comment by charlieartist** [comment]
@bheatonf1 That's what I need to find out. I know the menu is set up using mainly CSS3 animations, will need to debug to get to the bottom of this.

**Comment by bheatonf1** [comment]
funky... something must be hiding it
