### ISSUE TITLE
Static the 2016 site

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#48]
## Business Requirements

() Create a static copy of the 2016 site
## Technical Requirements

() ensure that the main robots.txt prevents it from being crawled.
() add a directory in github for "static_legacy_sites"
() place the static at /2016.
() use htaccess magic to serve the static_legacy_sites/2016 from /2016
() setup a 301 redirect from /drupal-govcon-2016 to /2016
() Remove login links from the pages
## Testing Instructions

() Confirm that there are no absolute paths.
() Run a link checker on the site and confirm that there are no broken links.
() Skim some of the pages on the site and look for broken javascript.  Attempt to fix if possible. If not investigate removing functionality.

**Comment by mikemadison13** [comment]
current status: I am following the basic directions on https://www.drupal.org/node/27882.

I have a local copy of the site in a VM and used wget to pull everything out. The biggest issue currently is that all files have hard coded urls to the prod url. These either need to be changed or they need to be replaced with the new relative url.

**Comment by aweingarten** [comment]
@mikemadison13 you should be able to do a quick find replace in PHPstorm to get that done without too much pain and suffering

**Comment by mikemadison13** [comment]
yeah @aweingarten, it's more a question of "what to make it"

**Comment by timwood** [comment]
@mikemadison13 an you document which tool you used from the directions on d.o. and the exact command and anything else that might be useful?

**Comment by mikemadison13** [comment]
Essentially:

1.  setup local copy of site (including repo, vm, files, and db). note: the 2016 version of the site has an older version of DrupalVM and I couldn't actually provision it. I instead used the 2017 d8 site's VM temporarily for the 2016 site.
2. installed wget using homebrew
3. installed the disable all forms module (http://drupal.org/project/disable_all_forms)
3. ran wget:
`wget -q --mirror -p --adjust-extension -e robots=off --base=./ -k -P ./ http://example.com`
4. Did some basic search / replace methods to get rid of the hard coded URL for the site

**Comment by mikemadison13** [comment]
current activity is trying to get the .htaccess redirects working per @aweingarten's request.

**Comment by timwood** [comment]
I've just committed PR #77 for the 2015 site. The changes to .htaccess will likely conflict with yours, but we should be able to resolve that relatively easily. I included these lines as well to catch the path with and without the / (slash) since in my environment it wasn't loading index.html.

```
  RewriteCond %{REQUEST_URI} ^/drupal-govcon-2015 [NC]
  RewriteRule ^drupal-govcon-2015/?$  /drupal-govcon-2015/index.html [NC,R,L]
  # Redirect GovCon 2015 path with or without / to index.html
```

**Comment by mikemadison13** [comment]
Update: Due to issues with the original WGet method, I've gone with the same HTTrack method that @timwood used. However, that method failed against the public stage/prod sites, so I had to rebuild my local environment.

**Comment by aweingarten** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/60
