### ISSUE TITLE
Create Non-Session Events

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/Drupal-GovCon-2017#482]
Non-session events need to have a way to be added to the schedule. These events would include things like Break, Registration, and Lunch.  The events would have start (and end) times as well as a location and a description (body?) field. 

Ideally - non session events would be displayed on the schedule in the appropriate day/time spot they are assigned to.  (Backup plan: Message at the top of each schedule page with clear info about break and lunch times.)

Need to consider how we treat events with the same name (i.e. Break - if day/time is the only differentiation, then content owners will just need to pay extra attention)

These non-session events do NOT include keynotes. Keynotes are treated as sessions in the keynote track.

**Comment by jdearie** [comment]
Keynotes will be added as session nodes. Other event types would be added here. (Registration, Breaks, etc). 

If we can't make the turn - static text can be added to the top of the schedule to identify the daily times for breaks, lunch etc)

**Comment by alisonjo2786** [comment]
@jdearie "Other event types would be added here" -- meaning?

But also, Jess, could you please wipe out the GH issue description here, and explain the intended plan for going forward?  Karl's original description talks about creating a new content type.

**Comment by alisonjo2786** [comment]
(one more question) @jdearie Is there a blocker for adding Keynotes as session nodes, do we have the content and necessary node/views structure, or are we missing one or both?

**Comment by jdearie** [comment]
@alisonjo2786 - keynotes will be session nodes. the only reason they aren't there yet is b/c i'm waiting on content.  keynote was added to the track vocab - so everything should work the same with the schedule... i presume.
