### ISSUE TITLE
UNSET ticket registration limit

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#488]
Changed live, but needs to be changed in code / in dev.  (Submission limit field should be empty.)
![image](https://user-images.githubusercontent.com/2660348/28175979-c8cdae88-67c3-11e7-9874-11d4a0600734.png)

relates to #489

**Comment by bheatonf1** [comment]
[PR](https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/514)
