### ISSUE TITLE
Ticket Waitlist

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#489]
Reg limit is 1400 -- then ticket reg form becomes "waitlist registration form."

NOTE: Maybe create follow-up tickets for "after we reach 1400" tasks, so that this ticket can be closed.

### Brooke:
* Add "is waitlist" boolean to ticket reg form.
  * Hidden/admin-only
  * Default value = "no / empty"
* Adjust "my tickets" view that's shown on user profile to show indication if a ticket is a waitlist ticket (just another column, or whatever is EASIEST).
* AFTER WE REACH 1400...
  * Default value = "yes"
  * Add explanation/text to webform page, based on #507 

###  Alison:
* Maybe create a rule or webform config to have the email sent automatically when someone is un-waitlisted.
  * **Brooke**, pls don't worry about this, even though I'm sure you could do it :)  I'll be fine, and if I have time, I'll do this and let you know :)
* Maybe create a view or something to help manage waitlist -- but this is optional / if time allows.
* AFTER WE REACH 1400...
  * Ping content ppl to do news/announcement about waitlist.
  * Commence keeping track of ticket deletions and moving ppl off of waitlist and sending emails to those people to let them know they're off the waitlist.

**Comment by bheatonf1** [comment]
@jdearie can this be closed? I think the only registration issue is the ability to delete one's own registration.

**Comment by jdearie** [comment]
not yet - we need to fix the wait list display issue (tickets are created and even though they are not on the wait list - the user profile page says they are).

![image](https://user-images.githubusercontent.com/5174534/28318576-4a821b7a-6b99-11e7-95f1-ba1e3276137f.png)

**Comment by bheatonf1** [comment]
@jdearie this should be resolved on DEV

**Comment by onelittlebecca** [comment]
w00t! clearing tickets like a boss @bheatonf1 !!!
