### ISSUE TITLE
Create a My Schedule

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#492]
Create a view where a user can see accepted sessions they have flagged 

The view display should match that of the current schedule (filtered by sessions user has flagged)

A tab or link to My Schedule should be accessible from the Schedule page.

**Comment by charlieartist** [comment]
I believe this continues on the work of the existing scheduling tickets.

**Comment by bheatonf1** [comment]
[PR](https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/525) @lkopacz you have time :/

**Comment by alisonjo2786** [comment]
@bheatonf1 I'm surprised there isn't an "add to my schedule" link on the Sessions view -- *if* this was already discussed, then 100% never mind, no need to re-hash just b/c I missed it.  If it wasn't discussed, is it doable very quickly/with minimal extra effort at this stage in the work, or should I add a new ticket and mark it for 2018, or?  Thanks!

**Comment by alisonjo2786** [comment]
@bheatonf1 We/You can close this issue, correct?

cc @dmkelner

**Comment by bheatonf1** [comment]
@jdearie let's add a ticket to add the link - i presume that would be a menu content/non-dev issue - then let's close this ticket.
