### ISSUE TITLE
Remove hyperlink to Track taxonomy page from session teaser on Schedule view

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#493]
The schedule view displays the track each session is assigned to and links to the term view for that track.

The term view is not set up to filter out non-accepted sessions. 

Easiest fix is to remove the hyperlink and display the just the text of the track

**Comment by bheatonf1** [comment]
[PR](https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/513)
