### ISSUE TITLE
add conference role to user account

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#499]
add a conference role field to the user account 

options:
-attendee (default)
-organizer
-volunteer

**Comment by charlieartist** [comment]
This will be addressed in [this issue](https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/477)

**Comment by charlieartist** [comment]
As noted in the references above, this issue is addressed in [issue 543](https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/543)
