### ISSUE TITLE
create a view of all organizers

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#500]
create a view of all user accounts that have the conference role of "organizer" in a photo grid

Fields should be:
user photo
d.o username
first name last name

relates to #499

**Comment by charlieartist** [comment]
This is being addressed in [this issue](https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/477)

**Comment by bheatonf1** [comment]
If this ticket is no longer needed, can we close this ticket @charlieartist ?
