### ISSUE TITLE
Language for waitlist things (webform, email notification, etc.)

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#507]
Once ticket webform submissions reach 1400, the webform will be modified to waitlist.  The language on the page when submissions are waitlisted should be:
> Thank you for your interest in Drupal GovCon.  Unfortunately, we have sold out!  Please complete the ticket registration below to be put on our waitlist.
> As users cancel their tickets, new tickets will be distributed to our waitlist in sequential order.  You will receive an email confirmation if your name is moved from the waitlist to registered.
> Add drupal4gov@gmail.com to your email contacts to make sure the message doesn't get filtered as spam!

Language for email when user moves from waitlist to ticketed:
> Congratulations!  You've been moved from the waitlist to our list of ticketed users! If you are no longer able to attend Drupal GovCon, please delete your ticket so that someone else can take your place. *[link to page on how to delete your ticket]*

**Comment by jdearie** [comment]
i still need to create the instructions page on how to delete your ticket, but I can't do that until users can actually delete their webform submissions.  they can't on prod yet. relates to #421

**Comment by alisonjo2786** [comment]
@bheatonf1 I was able to register and then delete my ticket using the "Cancel" link, woo-hoo!
