### ISSUE TITLE
When "user sessions" is empty, hide block

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#528]
Currently, it shows the "empty results text" from back when we were still pushing ppl to submit sessions, but now it should hide the block completely.

https://www.drupalgovcon.org/user
![image](https://user-images.githubusercontent.com/2660348/28440545-bc8fd86a-6d74-11e7-9cdc-1c370bb7368a.png)

**Comment by alisonjo2786** [comment]
@jdearie Could you please let us know how you'd like this prioritized?  Do you care that it's done before the Con, or should we put it in the 2018 list?

cc @charlieartist

**Comment by bheatonf1** [comment]
@jdearie @charlieartist I have a quick fix for this - will commit today.

**Comment by alisonjo2786** [comment]
@bheatonf1 @charlieartist Did y'all already get to this?
