### ISSUE TITLE
My Session Schedule: follow-up fixes

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#532]
* Grouping fix
* Sort improvement

**Comment by alisonjo2786** [comment]
Updated "my sessions" and "session schedule" views are [attached](https://github.com/Drupal4Gov/Drupal-GovCon-2017/files/1166204/sessions-views.ajm-20170721.zip).

Change details:
- Both:
   - Added "Content: Title" as secondary sort criteria.
   - Changed row style ("type") from entity:node to fields -- there were already fields on the view, I think this row style situation was just an artifact prior attempts at this view (i.e. before the grouping).
- my_sessions_schedule
   - General:
     - Cleaned out "master display" artifacts, now that this view is on its own, and not a secondary display on sessions_schedule.
       - (that's all the removed settings you'll see -- things that were part of sessions_schedule and carried over in the background in the my_sessions_schedule "master" display)
     - Changed "flag" relationship to "any user" (doesn't negatively impact filtering, and makes testing a lot easier!), and updated admin title to be more descriptive.
   - Date grouping things:
     - "Excluded from display" all fields except "Content: Rendered entity".
     - Added one more Date/Time field to view output :) -> field_session_date_time_2 -> I replicated the field_session_date_time_1 settings for displaying this field, i.e. "Long date format" and no label and "Group results together" aggregation settings.
     - Moved new date/time field, field_session_date_time_2, up above field_session_date_time_1.
     - Changed field_session_date_time_1 > aggregation settings to "COUNT(DISTINCT)".
     - Changed field_session_date_time_1 > (regular field settings) > "alter_text" (rewrite results) > `{{ field_session_date_time_2 }}`, and updated admin title to reflect changes.
     - View display > Row style options > Grouping > kept these settings as-is.
       - (I just felt like I should explicitly say "these stay as-is" b/c of all the complicated changes that are directly related to these row style settings.)
       - (For the record, "as is" = grouping field 1 is field_session_date_time_1, grouping field 2 is field_session_date_time.)

**Comment by charlieartist** [comment]
I'm creating a new branch to add in @alisonjo2786 and test. Will post that info momentarily.

**Comment by bheatonf1** [comment]
NICE WORK @alisonjo2786 ! It looks great!!

**Comment by alisonjo2786** [comment]
Awww thanks! :D
