### ISSUE TITLE
Add link to 'My Schedule' from main Schedule

### ISSUE THREAD

**Issue by brooke-heaton** [Drupal4Gov/Drupal-GovCon-2017#538]
@jdearie - please specify where this link should be located - screenshot etc.

**Comment by alisonjo2786** [comment]
@bheatonf1 And vice versa, I think -- I know "schedule" has a menu link, but still, there should be a link to the main Schedule from My Schedule, right....?

(could reuse whatever markup/styling y'all use for adding the link FROM schedule TO my schedule?)
