### ISSUE TITLE
Presenters View Bug

### ISSUE THREAD

**Issue by mikemadison13** [Drupal4Gov/Drupal-GovCon-2017#548]
The presenters view currently has multiple duplicates for many users. This is an artifact of the multiple relationships on the view.

It should probably be rebuilt to be based on either users or the approved sessions instead of the webform registrations, as the 3way relationships in the view are causing the dupes.

I have tried enabling aggregation and this is causing a fatal error re: the picture field (see https://www.drupal.org/node/2815881 as this is a core bug) and, as far as I can tell, aggregation and views distinct aren't helping in this case anyway.

**Comment by charlieartist** [comment]
@mikemadison13 how should this be tackled?
