### ISSUE TITLE
Add 2018 dates to home page

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/Drupal-GovCon-2017#551]
Please update the home page to change the current dates to next year's: Aug 22-24

So this:
2018 Dates Announced
August 22 - 24, 218
National Institutes of Health Campus
Natcher Conference Center • Bethesda, MD

replaces this
July 31 - August 2
National Institutes of Health Campus
Natcher Conference Center • Bethesda, MD

**Comment by charlieartist** [comment]
This is a custom block, will get the changes in for this.

**Comment by charlieartist** [comment]
@mikemadison13 One thing on this--IIRC, since the content is under the category Capital Camp Blocks, there is a custom hook required to pull this in, correct? 

At the moment, I've made the changes to the styleguide, but know there is another task needed to pull this new content into the layout.
