### ISSUE TITLE
Default the drupalvm ssh path to /var/www/capitalcamp

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#67]
Update config .yml so that when you ssh into the vm the default path is set to /var/www/capitalcamp

**Comment by timwood** [comment]
Do you suggest adjusting local ssh config or adding something to the vagrant users .bashrc? There's a risk the NFS mount won't have worked and so nothing will be in /var/www/capitalcamp, but I suppose the directory will still exist if that happens?

**Comment by aweingarten** [comment]
@timwood there is a setting we can add to the vm config.yml.

**Comment by aweingarten** [comment]
https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/83
