### ISSUE TITLE
As a site owner I want to ensure that my site loads as quickly as possible

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#74]
Analyze the site for front-end performance bottlenecks and create follow up tickets to address
- Confirm that content is cached at cloudflare.
- Confirm that bigpipe enabled.
- Run Frontend performance tests and look for opportunities to optimize.

**Comment by timwood** [comment]
BigPipe for perceived performance improvement!
