### ISSUE TITLE
Upgrade to Lightning distro

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#78]
https://www.drupal.org/project/lightning/releases/8.x-1.12

Does BLT or Composer do this for us automatically?

**Comment by aweingarten** [comment]
Currently we are tracking the dev branch of lightning.  

Probably should change to `^8.1` here:
https://github.com/Drupal4Gov/Drupal-GovCon-2017/blob/master/composer.json#L18

Then run `composer update drupal/lightning`

Finally commit composer.json and composer.lock
