### ISSUE TITLE
2015 + 2016 Static File Closeout

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#79]
- [ ] Update sitemap.xml settings to add weights to make 2015 and 2016 site lower than the rest of the site.
- [x] Add 301 redirects OR HTACCESS rewrites from/2015 and /2016 to /drupal-govcon-2016 and drupal-govcon-2015 
- [x]  in robots.txt exclude everything that's not a session page if possible

**Comment by mikemadison13** [comment]
couple of questions, is there a standard approach for putting NON drupal content into the XML Sitemap? I've never done that before an am not finding a great deal of information on doing so.

**Comment by mikemadison13** [comment]
i just added the 2015 and 2016 redirects as part of the other PR work being done for DGC-48. See https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/91

**Comment by timwood** [comment]
> Update sitemap.xml settings to add weights to make 2015 and 2016 site lower than the rest of the site.

Can the Drupal-generated sitemap.xml contain non-Drupal content?
