### ISSUE TITLE
Determine How to handle confidential keys on a public repo

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#86]

**Comment by timwood** [comment]
https://www.drupal.org/project/lockr

**Comment by aweingarten** [comment]
@timwood,
so the issue with settings.php is that is that it loads before the drupal container is bootstrapped.  That means that whatever solution we go with probably has to be a composer library which is autoloaded before we reach settings.php.  

It would probably involve a simple include from settings.php which has a decrypt function.  We could store the decryption key on the web-server outside git.  We could then simply put the encrytped values in settings wrapped in the decrypt function.   I'm going to talk with the BLT folks to see if this is something they might want.

**Comment by aweingarten** [comment]
@timwood,
I created a couple of new issues on the BLT issue queue:
- https://github.com/acquia/blt/issues/663
- https://github.com/acquia/blt/issues/659
