### ISSUE TITLE
Add static content pages to dev site

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2017#88]
Navigation from 2015 site (sorry for caps):

- ABOUT
  - CONTACT US
  - ~~ACCESSIBILITY~~
  - ~~TRAVEL AND DIRECTIONS~~ [_Called "Location"_]
  - WHERE TO STAY
  - ~~CODE OF CONDUCT~~
  - ~~CONVINCE YOUR BOSS~~
  - FAQS
- VOLUNTEERING!
  - MEET THE DRUPAL GOVCON TEAM
- SCHEDULE
  - MY SCHEDULE
  - BOFS
  - FLOOR LAYOUTS
  - ACCEPTED SESSIONS
- PROGRAM
  - CODE SPRINT
  - FULL DAY TRAININGS
  - ~~MENTORING~~
  - ~~SOCIAL EVENTS~~
- SPONSORS
- ~~SCHOLARSHIPS~~

Research other sites

- https://www.drupalcampnj.org/
- https://2016.badcamp.net/
- http://2016.drupalcorn.org/
- http://drupalcamp.london/
- https://www.fldrupal.camp/
- https://www.sandcamp.org/
- http://2016.midcamp.org/

Poll attendees using interactive design comps.

**Comment by timwood** [comment]
@prynncamm please review 2015 nav in issue and suggest any changes/merges/modifications. Any other feedback related to 2016 site nav that might apply to 2015.

**Comment by timwood** [comment]
@aweingarten Just want to confirm that we want to copy/paste/migrate any static pages to the new D8 site Development environment in Acquia hosting.

**Comment by timwood** [comment]
Items crossed out in issue description have been migrated/created in new dev site.

**Comment by aweingarten** [comment]
Removed scavenger hunt.  Since there won't be on in 2017!

**Comment by timwood** [comment]
Thanks! I wasn't sure about that one.

**Comment by jdearie** [comment]
Here's the 2017 IA:

HOME

ABOUT
What is Drupal GovCon? 
Ticket Info 
Important Dates
Schedule at a Glance
Accessibility
About Drupal4Gov
News

PROGRAM
Become a Speaker
Propose a Training
Sprints 
Birds of a Feather
Mentoring 
Social Events
Session Tracks
Proposed Sessions

TRAVEL
Hotels 
Getting Here
Visit the DMV
Travel Discounts 

COMMUNITY
Code of Conduct
Looks Who’s Coming (dynamic page of registered attendees)
Apply for a Scholarship (maybe)
Sign up to be a Sprint Mentor
Meet the Drupal GovCon Team (dynamic page of organizers)

SPONSORS
Become a Sponsor
Our Sponsors

REGISTER!

LOG OUT
MY ACCOUNT

**Comment by aweingarten** [comment]
done
