### ISSUE TITLE
Scrub The DB when pulling it down from PROD

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#93]
## Business Requirements 
- As a user I want my PII protected.

## Technical Requirements
- Write a cloudhook which fires on DB activity for NON prod environments
- have it scrub the user's table with random emails and passwords.
- Scrub the cloudflare settings
- Scrub the acquia config settings
- Update the travis build to pulldown the DB from stage

**Comment by mikemadison13** [comment]
the BLT 8.6.6 approach now automatically sanitizes the database on the post db update cloud hook. 

i've started experimenting with how to clear the acquia connector and cloudflare config. one method is to uninstall / reinstall the modules using a cloud hook. @aweingarten and I have also discussed writing a custom hook for sql-sanitize (which I have started but the query isn't working) to wipe the config that way.
